package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

/**
 * AbogadoEstudio generated by hbm2java
 */
public class AbogadoEstudio implements java.io.Serializable {

	private AbogadoEstudioId id;
	private Abogado abogado;
	private Estudio estudio;
	private Character estado;

	public AbogadoEstudio() {
	}

	public AbogadoEstudio(AbogadoEstudioId id, Abogado abogado, Estudio estudio) {
		this.id = id;
		this.abogado = abogado;
		this.estudio = estudio;
	}

	public AbogadoEstudio(AbogadoEstudioId id, Abogado abogado,
			Estudio estudio, Character estado) {
		this.id = id;
		this.abogado = abogado;
		this.estudio = estudio;
		this.estado = estado;
	}

	public AbogadoEstudioId getId() {
		return this.id;
	}

	public void setId(AbogadoEstudioId id) {
		this.id = id;
	}

	public Abogado getAbogado() {
		return this.abogado;
	}

	public void setAbogado(Abogado abogado) {
		this.abogado = abogado;
	}

	public Estudio getEstudio() {
		return this.estudio;
	}

	public void setEstudio(Estudio estudio) {
		this.estudio = estudio;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
