package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * ActividadProcesal generated by hbm2java
 */
public class ActividadProcesal implements java.io.Serializable {

	private long idActividadProcesal;
	private Etapa etapa;
	private SituacionActProc situacionActProc;
	private Actividad actividad;
	private String plazoLey;
	private Timestamp fechaActividad;
	private Date fechaActividadAux;
	private Date fechaAtencionAux;
	
	private Timestamp fechaVencimiento;
	private Date fechaVencimientoAux;

	private Date fechaAtencion;
	private String responsable;
	private String observacion;
	private Character estado;

	private Expediente expediente;
	
	private String fechaActividadToString;
	private String fechaVencimientoToString;
	private String fechaAtencionToString;
	
	private int numero;
	
	
	

	public ActividadProcesal(long idActividadProcesal, Etapa etapa,
			SituacionActProc situacionActProc, Actividad actividad,
			String plazoLey, Timestamp fechaActividad, Date fechaActividadAux,
			Date fechaAtencionAux, Timestamp fechaVencimiento,
			Date fechaVencimientoAux, Date fechaAtencion, String responsable,
			String observacion, Character estado, Expediente expediente,
			String fechaActividadToString, String fechaVencimientoToString,
			String fechaAtencionToString, int numero) {
		super();
		this.idActividadProcesal = idActividadProcesal;
		this.etapa = etapa;
		this.situacionActProc = situacionActProc;
		this.actividad = actividad;
		this.plazoLey = plazoLey;
		this.fechaActividad = fechaActividad;
		this.fechaActividadAux = fechaActividadAux;
		this.fechaAtencionAux = fechaAtencionAux;
		this.fechaVencimiento = fechaVencimiento;
		this.fechaVencimientoAux = fechaVencimientoAux;
		this.fechaAtencion = fechaAtencion;
		this.responsable = responsable;
		this.observacion = observacion;
		this.estado = estado;
		this.expediente = expediente;
		this.fechaActividadToString = fechaActividadToString;
		this.fechaVencimientoToString = fechaVencimientoToString;
		this.fechaAtencionToString = fechaAtencionToString;
		this.numero = numero;
	}

	public ActividadProcesal() {
	}
	
	public Date getFechaVencimientoAux() {
		return fechaVencimientoAux;
	}
	
	
	public void setFechaVencimientoAux(Date fechaVencimientoAux) {
		
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
		
		if(fechaVencimientoAux == null){
			setFechaVencimientoToString("");
			
		}else{
			setFechaVencimiento(new Timestamp(fechaVencimientoAux.getTime()));
			setFechaVencimientoToString(dateFormat.format(fechaVencimientoAux));
		}

		this.fechaVencimientoAux = fechaVencimientoAux;
	}
	

	public ActividadProcesal(Etapa etapa, SituacionActProc situacionActProc,
			Actividad actividad) {
		super();
		this.etapa = etapa;
		this.situacionActProc = situacionActProc;
		this.actividad = actividad;
	}

	public ActividadProcesal(long idActividadProcesal) {
		this.idActividadProcesal = idActividadProcesal;
	}

	

	public long getIdActividadProcesal() {
		return this.idActividadProcesal;
	}

	public void setIdActividadProcesal(long idActividadProcesal) {
		this.idActividadProcesal = idActividadProcesal;
	}

	public Etapa getEtapa() {
		return this.etapa;
	}

	public void setEtapa(Etapa etapa) {
		this.etapa = etapa;
	}

	public SituacionActProc getSituacionActProc() {
		return this.situacionActProc;
	}

	public void setSituacionActProc(SituacionActProc situacionActProc) {
		this.situacionActProc = situacionActProc;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public String getPlazoLey() {
		return this.plazoLey;
	}

	public void setPlazoLey(String plazoLey) {
		this.plazoLey = plazoLey;
	}

	
	public void setFechaActividad(Timestamp fechaActividad) {
		this.fechaActividad = fechaActividad;
	}

	public Timestamp getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Timestamp fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	public Date getFechaAtencion() {
		return this.fechaAtencion;
	}

	public void setFechaAtencion(Date fechaAtencion) {
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		
		if(fechaAtencion == null){
			setFechaAtencionToString("");
		}else{
			setFechaAtencionToString(dateFormat.format(fechaAtencion));
		}
		

		this.fechaAtencion = fechaAtencion;
	}

	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public String getFechaActividadToString() {
		return fechaActividadToString;
	}

	public void setFechaActividadToString(String fechaActividadToString) {
		this.fechaActividadToString = fechaActividadToString;
	}

	public String getFechaVencimientoToString() {
		return fechaVencimientoToString;
	}

	public void setFechaVencimientoToString(String fechaVencimientoToString) {
		this.fechaVencimientoToString = fechaVencimientoToString;
	}

	public String getFechaAtencionToString() {
		return fechaAtencionToString;
	}

	public void setFechaAtencionToString(String fechaAtencionToString) {
		this.fechaAtencionToString = fechaAtencionToString;
	}

	public Expediente getExpediente() {
		return expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Timestamp getFechaActividad() {
		return fechaActividad;
	}

	public Date getFechaActividadAux() {
		return fechaActividadAux;
	}

	public void setFechaActividadAux(Date fechaActividadAux) {
		
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
		
		if(fechaActividadAux == null){
			setFechaActividadToString("");
			
		}else{
			setFechaActividad(new Timestamp(fechaActividadAux.getTime()));
			setFechaActividadToString(dateFormat.format(fechaActividadAux));
		}

		this.fechaActividadAux = fechaActividadAux;
	}
	
	
	

	public Date getFechaAtencionAux() {
		return fechaAtencionAux;
	}
	
	public void setFechaAtencionAux(Date fechaAtencionAux) {
		
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
		
		if(fechaAtencionAux == null){
			setFechaActividadToString("");
			
		}else{
			setFechaAtencion(new Timestamp(fechaAtencionAux.getTime()));
			setFechaAtencionToString(dateFormat.format(fechaAtencionAux));
		}

		this.fechaAtencionAux = fechaAtencionAux;
	}

	public int getNumero() {
		return numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

}
