package com.hildebrando.legal.modelo;

// Generated 28-sep-2012 16:17:56 by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import org.primefaces.model.UploadedFile;

/**
 * Anexo generated by hbm2java
 */
public class Anexo implements java.io.Serializable {

	private int idDocumento;
	private Expediente expediente;
	private String titulo;
	private String comentario;
	private Date fechaInicio;

	private String fechaToString;
	
	private String formato;
	private String ubicacion;
	
	private byte[] bytes;
	
	public Anexo() {
	}

	public Anexo(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	public Anexo(int idDocumento, Expediente expediente, String titulo,
			String comentario, Date fechaInicio, String formato, String ubicacion) {
		this.idDocumento = idDocumento;
		this.expediente = expediente;
		this.titulo = titulo;
		this.comentario = comentario;
		this.fechaInicio = fechaInicio;
		this.formato = formato;
		this.ubicacion = ubicacion;
	}

	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getFechaToString() {
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		setFechaToString(dateFormat.format(getFechaInicio()));

		return fechaToString;
	}

	public void setFechaToString(String fechaToString) {
		this.fechaToString = fechaToString;
	}

	public String getFormato() {
		return formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}

	public String getUbicacion() {
		return ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public byte[] getBytes() {
		return bytes;
	}

	public void setBytes(byte[] bytes) {
		this.bytes = bytes;
	}



}
