package com.hildebrando.legal.modelo;

// Generated 24-ago-2012 16:27:14 by Hibernate Tools 3.4.0.CR1

/**
 * Aviso generated by hbm2java
 */
public class Aviso implements java.io.Serializable {

	private int idAviso;
	private Via via;
	private Proceso proceso;
	private Actividad actividad;
	private Character color;
	private Integer dias;

	public Aviso() {
	}

	public Aviso(int idAviso) {
		this.idAviso = idAviso;
	}

	public Aviso(int idAviso, Via via, Proceso proceso, Actividad actividad,
			Character color, Integer dias) {
		this.idAviso = idAviso;
		this.via = via;
		this.proceso = proceso;
		this.actividad = actividad;
		this.color = color;
		this.dias = dias;
	}

	public int getIdAviso() {
		return this.idAviso;
	}

	public void setIdAviso(int idAviso) {
		this.idAviso = idAviso;
	}

	public Via getVia() {
		return this.via;
	}

	public void setVia(Via via) {
		this.via = via;
	}

	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Character getColor() {
		return this.color;
	}

	public void setColor(Character color) {
		this.color = color;
	}

	public Integer getDias() {
		return this.dias;
	}

	public void setDias(Integer dias) {
		this.dias = dias;
	}

}
