package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion implements java.io.Serializable {

	private BigDecimal idCalificacion;
	private String nombre;
	private Set expedientes = new HashSet(0);

	public Calificacion() {
	}

	public Calificacion(BigDecimal idCalificacion) {
		this.idCalificacion = idCalificacion;
	}

	public Calificacion(BigDecimal idCalificacion, String nombre,
			Set expedientes) {
		this.idCalificacion = idCalificacion;
		this.nombre = nombre;
		this.expedientes = expedientes;
	}

	public BigDecimal getIdCalificacion() {
		return this.idCalificacion;
	}

	public void setIdCalificacion(BigDecimal idCalificacion) {
		this.idCalificacion = idCalificacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

}
