package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Cuantia generated by hbm2java
 */
public class Cuantia implements java.io.Serializable {

	private BigDecimal idCuantia;
	private Moneda moneda;
	private Materia materia;
	private Expediente expediente;
	private Integer pretendido;

	public Cuantia() {
	}

	public Cuantia(BigDecimal idCuantia) {
		this.idCuantia = idCuantia;
	}

	public Cuantia(BigDecimal idCuantia, Moneda moneda, Materia materia,
			Expediente expediente, Integer pretendido) {
		this.idCuantia = idCuantia;
		this.moneda = moneda;
		this.materia = materia;
		this.expediente = expediente;
		this.pretendido = pretendido;
	}

	public BigDecimal getIdCuantia() {
		return this.idCuantia;
	}

	public void setIdCuantia(BigDecimal idCuantia) {
		this.idCuantia = idCuantia;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Integer getPretendido() {
		return this.pretendido;
	}

	public void setPretendido(Integer pretendido) {
		this.pretendido = pretendido;
	}

}
