package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private long idCuota;
	private Integer numero;
	private String nroRecibo;
	private Double importe;
	private Date fechaPago;
	private SituacionCuota situacionCuota;
	private Honorario honorario;
	
	private String moneda;
	
	private boolean flagPendiente;
	

	private String fechaToString;
	
	public String getFechaToString() {
		return fechaToString;
	}

	public void setFechaToString(String fechaToString) {
		this.fechaToString = fechaToString;
	}

	
	public Cuota() {
	}

	public Cuota(long idCuota) {
		this.idCuota = idCuota;
	}

	public Cuota(long idCuota, Honorario honorario,
			SituacionCuota situacionCuota, Integer numero, String nroRecibo,
			Double importe, Date fechaPago) {
		this.idCuota = idCuota;
		this.honorario = honorario;
		this.situacionCuota = situacionCuota;
		this.numero = numero;
		this.nroRecibo = nroRecibo;
		this.importe = importe;
		this.fechaPago = fechaPago;
	}

	public long getIdCuota() {
		return this.idCuota;
	}

	public void setIdCuota(long idCuota) {
		this.idCuota = idCuota;
	}

	public Honorario getHonorario() {
		return this.honorario;
	}

	public void setHonorario(Honorario honorario) {
		this.honorario = honorario;
	}

	public SituacionCuota getSituacionCuota() {
		return this.situacionCuota;
	}

	public void setSituacionCuota(SituacionCuota situacionCuota) {
		this.situacionCuota = situacionCuota;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getNroRecibo() {
		return this.nroRecibo;
	}

	public void setNroRecibo(String nroRecibo) {
		this.nroRecibo = nroRecibo;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}
	

	public Date getFechaPago() {
		if(fechaPago == null){
			Calendar cal = Calendar.getInstance();
			fechaPago = cal.getTime();
		}
		return fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		setFechaToString(dateFormat.format(fechaPago));

		this.fechaPago = fechaPago;
	}

	public String getMoneda() {
		return moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public boolean isFlagPendiente() {
		return flagPendiente;
	}

	public void setFlagPendiente(boolean flagPendiente) {
		this.flagPendiente = flagPendiente;
	}

}
