package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private int idCuota;
	private Honorario honorario;
	private SituacionCuota situacionCuota;
	private int numero;
	private String nroRecibo;
	private Double importe;
	private Date fechaPago;

	public Cuota() {
	}

	public Cuota(int idCuota) {
		this.idCuota = idCuota;
	}

	public Cuota(int idCuota, Honorario honorario,
			SituacionCuota situacionCuota, int numero, String nroRecibo,
			Double importe, Date fechaPago) {
		this.idCuota = idCuota;
		this.honorario = honorario;
		this.situacionCuota = situacionCuota;
		this.numero = numero;
		this.nroRecibo = nroRecibo;
		this.importe = importe;
		this.fechaPago = fechaPago;
	}

	public int getIdCuota() {
		return this.idCuota;
	}

	public void setIdCuota(int idCuota) {
		this.idCuota = idCuota;
	}

	public Honorario getHonorario() {
		return this.honorario;
	}

	public void setHonorario(Honorario honorario) {
		this.honorario = honorario;
	}

	public SituacionCuota getSituacionCuota() {
		return this.situacionCuota;
	}

	public void setSituacionCuota(SituacionCuota situacionCuota) {
		this.situacionCuota = situacionCuota;
	}

	public String getNroRecibo() {
		return this.nroRecibo;
	}

	public void setNroRecibo(String nroRecibo) {
		this.nroRecibo = nroRecibo;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public int getNumero() {
		return numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

}
