package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EstadoCautelar generated by hbm2java
 */
public class EstadoCautelar implements java.io.Serializable {

	private BigDecimal idEstadoCautelar;
	private String descripcion;
	private Set expedientes = new HashSet(0);

	public EstadoCautelar() {
	}

	public EstadoCautelar(BigDecimal idEstadoCautelar) {
		this.idEstadoCautelar = idEstadoCautelar;
	}

	public EstadoCautelar(BigDecimal idEstadoCautelar, String descripcion,
			Set expedientes) {
		this.idEstadoCautelar = idEstadoCautelar;
		this.descripcion = descripcion;
		this.expedientes = expedientes;
	}

	public BigDecimal getIdEstadoCautelar() {
		return this.idEstadoCautelar;
	}

	public void setIdEstadoCautelar(BigDecimal idEstadoCautelar) {
		this.idEstadoCautelar = idEstadoCautelar;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

}
