package com.hildebrando.legal.modelo;

// Generated 22-oct-2012 12:21:21 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Feriado generated by hbm2java
 */
public class Feriado implements java.io.Serializable {

	private int idFeriado;
	private Ubigeo ubigeo;
	private Organo organo;
	private Date fecha;
	private Character tipo;
	private Character indicador;
	private Character estado;
	private String fechaToString;
	private String fechaToStringSort;
	private String nombre;

	public Feriado() {
	}

	public Feriado(int idFeriado) {
		this.idFeriado = idFeriado;
	}

	public Feriado(int idFeriado, Ubigeo ubigeo, Organo organo,
			Date fecha, Character tipo, Character indicador) {
		this.idFeriado = idFeriado;
		this.ubigeo = ubigeo;
		this.organo = organo;
		this.fecha = fecha;
		this.tipo = tipo;
		this.indicador = indicador;
	}

	public int getIdFeriado() {
		return this.idFeriado;
	}

	public void setIdFeriado(int idFeriado) {
		this.idFeriado = idFeriado;
	}

	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	public Organo getOrgano() {
		return this.organo;
	}

	public void setOrgano(Organo organo) {
		this.organo = organo;
	}

	public Character getTipo() {
		return this.tipo;
	}

	public void setTipo(Character tipo) {
		this.tipo = tipo;
	}

	public Character getIndicador() {
		return this.indicador;
	}

	public void setIndicador(Character indicador) {
		this.indicador = indicador;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		DateFormat dateFormatSort = new SimpleDateFormat("yyyy/MM/dd");
		
		setFechaToString(dateFormat.format(fecha));
		setFechaToStringSort(dateFormatSort.format(fecha));
		
		this.fecha = fecha;
	}

	public String getFechaToString() {
		return fechaToString;
	}

	public void setFechaToString(String fechaToString) {
		this.fechaToString = fechaToString;
	}

	public String getFechaToStringSort() {
		return fechaToStringSort;
	}

	public void setFechaToStringSort(String fechaToStringSort) {
		this.fechaToStringSort = fechaToStringSort;
	}	
}
