package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 19:06:50 by Hibernate Tools 3.4.0.CR1

/**
 * FormaConclusion generated by hbm2java
 */
public class FormaConclusion implements java.io.Serializable {

	private int idFormaConclusion;
	private Hito hito;
	private String descripcion;

	public FormaConclusion() {
	}

	public FormaConclusion(int idFormaConclusion) {
		this.idFormaConclusion = idFormaConclusion;
	}

	public FormaConclusion(int idFormaConclusion, Hito hito, String descripcion) {
		this.idFormaConclusion = idFormaConclusion;
		this.hito = hito;
		this.descripcion = descripcion;
	}

	public int getIdFormaConclusion() {
		return this.idFormaConclusion;
	}

	public void setIdFormaConclusion(int idFormaConclusion) {
		this.idFormaConclusion = idFormaConclusion;
	}

	public Hito getHito() {
		return this.hito;
	}

	public void setHito(Hito hito) {
		this.hito = hito;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
