package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FormaConclusion generated by hbm2java
 */
public class FormaConclusion implements java.io.Serializable {

	private int idFormaConclusion;
	private String descripcion;
	private Set hitos = new HashSet(0);

	public FormaConclusion() {
	}

	public FormaConclusion(int idFormaConclusion) {
		this.idFormaConclusion = idFormaConclusion;
	}

	public FormaConclusion(int idFormaConclusion, String descripcion, Set hitos) {
		this.idFormaConclusion = idFormaConclusion;
		this.descripcion = descripcion;
		this.hitos = hitos;
	}

	public int getIdFormaConclusion() {
		return this.idFormaConclusion;
	}

	public void setIdFormaConclusion(int idFormaConclusion) {
		this.idFormaConclusion = idFormaConclusion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

}
