package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

/**
 * GrupoBanca generated by hbm2java
 */
public class GrupoBanca implements java.io.Serializable {

	private int idGrupoBanca;
	private Territorio territorio;

	public GrupoBanca() {
	}

	public GrupoBanca(int idGrupoBanca) {
		this.idGrupoBanca = idGrupoBanca;
	}

	public GrupoBanca(int idGrupoBanca, Territorio territorio) {
		this.idGrupoBanca = idGrupoBanca;
		this.territorio = territorio;
	}

	public int getIdGrupoBanca() {
		return this.idGrupoBanca;
	}

	public void setIdGrupoBanca(int idGrupoBanca) {
		this.idGrupoBanca = idGrupoBanca;
	}

	public Territorio getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

}
