package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * GrupoBanca generated by hbm2java
 */
public class GrupoBanca implements java.io.Serializable {

	private BigDecimal idGrupoBanca;
	private Territorio territorio;

	public GrupoBanca() {
	}

	public GrupoBanca(BigDecimal idGrupoBanca) {
		this.idGrupoBanca = idGrupoBanca;
	}

	public GrupoBanca(BigDecimal idGrupoBanca, Territorio territorio) {
		this.idGrupoBanca = idGrupoBanca;
		this.territorio = territorio;
	}

	public BigDecimal getIdGrupoBanca() {
		return this.idGrupoBanca;
	}

	public void setIdGrupoBanca(BigDecimal idGrupoBanca) {
		this.idGrupoBanca = idGrupoBanca;
	}

	public Territorio getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

}
