package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 19:06:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hito generated by hbm2java
 */
public class Hito implements java.io.Serializable {

	private long idHito;
	private Hito hito;
	private Expediente expediente;
	private Date fechaInicio;
	private Date fechaFin;
	private String comentario;
	private Character flagRevertir;
	private Set hitos = new HashSet(0);
	private Set actividadProcesals = new HashSet(0);
	private Set formaConclusions = new HashSet(0);

	public Hito() {
	}

	public Hito(long idHito) {
		this.idHito = idHito;
	}

	public Hito(long idHito, Hito hito, Expediente expediente,
			Date fechaInicio, Date fechaFin, String comentario,
			Character flagRevertir, Set hitos, Set actividadProcesals,
			Set formaConclusions) {
		this.idHito = idHito;
		this.hito = hito;
		this.expediente = expediente;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.comentario = comentario;
		this.flagRevertir = flagRevertir;
		this.hitos = hitos;
		this.actividadProcesals = actividadProcesals;
		this.formaConclusions = formaConclusions;
	}

	public long getIdHito() {
		return this.idHito;
	}

	public void setIdHito(long idHito) {
		this.idHito = idHito;
	}

	public Hito getHito() {
		return this.hito;
	}

	public void setHito(Hito hito) {
		this.hito = hito;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Character getFlagRevertir() {
		return this.flagRevertir;
	}

	public void setFlagRevertir(Character flagRevertir) {
		this.flagRevertir = flagRevertir;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

	public Set getActividadProcesals() {
		return this.actividadProcesals;
	}

	public void setActividadProcesals(Set actividadProcesals) {
		this.actividadProcesals = actividadProcesals;
	}

	public Set getFormaConclusions() {
		return this.formaConclusions;
	}

	public void setFormaConclusions(Set formaConclusions) {
		this.formaConclusions = formaConclusions;
	}

}
