package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Honorario generated by hbm2java
 */
public class Honorario implements java.io.Serializable {

	private long idHonorario;
	private Abogado abogado;
	private Moneda moneda;
	private Expediente expediente;
	private TipoHonorario tipoHonorario;
	private SituacionHonorario situacionHonorario;
	private Integer cuotas;
	private Double monto;
	private Double montoPagado;
	private String instancia;
	private Set cuotas_1 = new HashSet(0);

	public Honorario() {
	}

	public Honorario(long idHonorario) {
		this.idHonorario = idHonorario;
	}

	public Honorario(long idHonorario, Abogado abogado, Moneda moneda,
			Expediente expediente, TipoHonorario tipoHonorario,
			SituacionHonorario situacionHonorario, Integer cuotas,
			Double monto, Double montoPagado, String instancia, Set cuotas_1) {
		this.idHonorario = idHonorario;
		this.abogado = abogado;
		this.moneda = moneda;
		this.expediente = expediente;
		this.tipoHonorario = tipoHonorario;
		this.situacionHonorario = situacionHonorario;
		this.cuotas = cuotas;
		this.monto = monto;
		this.montoPagado = montoPagado;
		this.instancia = instancia;
		this.cuotas_1 = cuotas_1;
	}

	public long getIdHonorario() {
		return this.idHonorario;
	}

	public void setIdHonorario(long idHonorario) {
		this.idHonorario = idHonorario;
	}

	public Abogado getAbogado() {
		return this.abogado;
	}

	public void setAbogado(Abogado abogado) {
		this.abogado = abogado;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public TipoHonorario getTipoHonorario() {
		return this.tipoHonorario;
	}

	public void setTipoHonorario(TipoHonorario tipoHonorario) {
		this.tipoHonorario = tipoHonorario;
	}

	public SituacionHonorario getSituacionHonorario() {
		return this.situacionHonorario;
	}

	public void setSituacionHonorario(SituacionHonorario situacionHonorario) {
		this.situacionHonorario = situacionHonorario;
	}

	public Integer getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Integer cuotas) {
		this.cuotas = cuotas;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public Double getMontoPagado() {
		return this.montoPagado;
	}

	public void setMontoPagado(Double montoPagado) {
		this.montoPagado = montoPagado;
	}

	public String getInstancia() {
		return this.instancia;
	}

	public void setInstancia(String instancia) {
		this.instancia = instancia;
	}

	public Set getCuotas_1() {
		return this.cuotas_1;
	}

	public void setCuotas_1(Set cuotas_1) {
		this.cuotas_1 = cuotas_1;
	}

}
