package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Honorario generated by hbm2java
 */
public class Honorario implements java.io.Serializable {

	private BigDecimal idHonorario;
	private Abogado abogado;
	private Moneda moneda;
	private TipoHonorario tipoHonorario;
	private Expediente expediente;
	private SituacionHonorario situacionHonorario;
	private BigDecimal cuotas;
	private Integer monto;
	private Integer montoPagado;
	private String instancia;
	private Set cuotas_1 = new HashSet(0);

	public Honorario() {
	}

	public Honorario(BigDecimal idHonorario) {
		this.idHonorario = idHonorario;
	}

	public Honorario(BigDecimal idHonorario, Abogado abogado, Moneda moneda,
			TipoHonorario tipoHonorario, Expediente expediente,
			SituacionHonorario situacionHonorario, BigDecimal cuotas,
			Integer monto, Integer montoPagado, String instancia, Set cuotas_1) {
		this.idHonorario = idHonorario;
		this.abogado = abogado;
		this.moneda = moneda;
		this.tipoHonorario = tipoHonorario;
		this.expediente = expediente;
		this.situacionHonorario = situacionHonorario;
		this.cuotas = cuotas;
		this.monto = monto;
		this.montoPagado = montoPagado;
		this.instancia = instancia;
		this.cuotas_1 = cuotas_1;
	}

	public BigDecimal getIdHonorario() {
		return this.idHonorario;
	}

	public void setIdHonorario(BigDecimal idHonorario) {
		this.idHonorario = idHonorario;
	}

	public Abogado getAbogado() {
		return this.abogado;
	}

	public void setAbogado(Abogado abogado) {
		this.abogado = abogado;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public TipoHonorario getTipoHonorario() {
		return this.tipoHonorario;
	}

	public void setTipoHonorario(TipoHonorario tipoHonorario) {
		this.tipoHonorario = tipoHonorario;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public SituacionHonorario getSituacionHonorario() {
		return this.situacionHonorario;
	}

	public void setSituacionHonorario(SituacionHonorario situacionHonorario) {
		this.situacionHonorario = situacionHonorario;
	}

	public BigDecimal getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(BigDecimal cuotas) {
		this.cuotas = cuotas;
	}

	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

	public Integer getMontoPagado() {
		return this.montoPagado;
	}

	public void setMontoPagado(Integer montoPagado) {
		this.montoPagado = montoPagado;
	}

	public String getInstancia() {
		return this.instancia;
	}

	public void setInstancia(String instancia) {
		this.instancia = instancia;
	}

	public Set getCuotas_1() {
		return this.cuotas_1;
	}

	public void setCuotas_1(Set cuotas_1) {
		this.cuotas_1 = cuotas_1;
	}

}
