package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 * Inculpado generated by hbm2java
 */
public class Inculpado implements java.io.Serializable {

	private int idInculpado;
	private SituacionInculpado situacionInculpado;
	private Moneda moneda;
	private Persona persona;
	private Expediente expediente;
	private Date fecha;
	private Integer nrocupon;
	private Double monto;
	
	private String fechaToString;

	
	
	
	public Inculpado(SituacionInculpado situacionInculpado, Moneda moneda,
			Persona persona) {
		super();
		this.situacionInculpado = situacionInculpado;
		this.moneda = moneda;
		this.persona = persona;
	}

	public Inculpado() {
	}

	public Inculpado(int idInculpado) {
		this.idInculpado = idInculpado;
	}

	public Inculpado(int idInculpado, SituacionInculpado situacionInculpado,
			Moneda moneda, Persona persona, Expediente expediente, Date fecha,
			Integer nrocupon, Double monto) {
		this.idInculpado = idInculpado;
		this.situacionInculpado = situacionInculpado;
		this.moneda = moneda;
		this.persona = persona;
		this.expediente = expediente;
		this.fecha = fecha;
		this.nrocupon = nrocupon;
		this.monto = monto;
	}

	public int getIdInculpado() {
		return this.idInculpado;
	}

	public void setIdInculpado(int idInculpado) {
		this.idInculpado = idInculpado;
	}

	public SituacionInculpado getSituacionInculpado() {
		if(situacionInculpado ==null)
			situacionInculpado = new SituacionInculpado();
		return this.situacionInculpado;
	}

	public void setSituacionInculpado(SituacionInculpado situacionInculpado) {
		this.situacionInculpado = situacionInculpado;
	}

	public Moneda getMoneda() {
		if(moneda== null)
			moneda = new Moneda();
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getNrocupon() {
		return this.nrocupon;
	}

	public void setNrocupon(Integer nrocupon) {
		this.nrocupon = nrocupon;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public String getFechaToString() {
		SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
		fechaToString = format.format(getFecha());
		return fechaToString;
	}

	public void setFechaToString(String fechaToString) {
		this.fechaToString = fechaToString;
	}

}
