package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Inculpado generated by hbm2java
 */
public class Inculpado implements java.io.Serializable {

	private InculpadoId id;
	private SituacionInculpado situacionInculpado;
	private Moneda moneda;
	private Persona persona;
	private Expediente expediente;
	private BigDecimal idClase;
	private BigDecimal idTipoDocumento;
	private BigDecimal numeroDocumento;
	private BigDecimal codCliente;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombres;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private Serializable fechaCreacion;
	private Serializable fechaModificacion;
	private Serializable fecha;
	private BigDecimal nrocupon;
	private Integer monto;

	public Inculpado() {
	}

	public Inculpado(InculpadoId id, Persona persona) {
		this.id = id;
		this.persona = persona;
	}

	public Inculpado(InculpadoId id, SituacionInculpado situacionInculpado,
			Moneda moneda, Persona persona, Expediente expediente,
			BigDecimal idClase, BigDecimal idTipoDocumento,
			BigDecimal numeroDocumento, BigDecimal codCliente,
			String apellidoPaterno, String apellidoMaterno, String nombres,
			String usuarioCreacion, String usuarioModificacion,
			Serializable fechaCreacion, Serializable fechaModificacion,
			Serializable fecha, BigDecimal nrocupon, Integer monto) {
		this.id = id;
		this.situacionInculpado = situacionInculpado;
		this.moneda = moneda;
		this.persona = persona;
		this.expediente = expediente;
		this.idClase = idClase;
		this.idTipoDocumento = idTipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.codCliente = codCliente;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombres = nombres;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.fecha = fecha;
		this.nrocupon = nrocupon;
		this.monto = monto;
	}

	public InculpadoId getId() {
		return this.id;
	}

	public void setId(InculpadoId id) {
		this.id = id;
	}

	public SituacionInculpado getSituacionInculpado() {
		return this.situacionInculpado;
	}

	public void setSituacionInculpado(SituacionInculpado situacionInculpado) {
		this.situacionInculpado = situacionInculpado;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public BigDecimal getIdClase() {
		return this.idClase;
	}

	public void setIdClase(BigDecimal idClase) {
		this.idClase = idClase;
	}

	public BigDecimal getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public BigDecimal getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(BigDecimal numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public BigDecimal getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(BigDecimal codCliente) {
		this.codCliente = codCliente;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Serializable getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Serializable fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Serializable getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Serializable fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Serializable getFecha() {
		return this.fecha;
	}

	public void setFecha(Serializable fecha) {
		this.fecha = fecha;
	}

	public BigDecimal getNrocupon() {
		return this.nrocupon;
	}

	public void setNrocupon(BigDecimal nrocupon) {
		this.nrocupon = nrocupon;
	}

	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

}
