package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * InculpadoId generated by hbm2java
 */
public class InculpadoId implements java.io.Serializable {

	private BigDecimal idPersona;
	private BigDecimal idInculpado;

	public InculpadoId() {
	}

	public InculpadoId(BigDecimal idPersona, BigDecimal idInculpado) {
		this.idPersona = idPersona;
		this.idInculpado = idInculpado;
	}

	public BigDecimal getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(BigDecimal idPersona) {
		this.idPersona = idPersona;
	}

	public BigDecimal getIdInculpado() {
		return this.idInculpado;
	}

	public void setIdInculpado(BigDecimal idInculpado) {
		this.idInculpado = idInculpado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InculpadoId))
			return false;
		InculpadoId castOther = (InculpadoId) other;

		return ((this.getIdPersona() == castOther.getIdPersona()) || (this
				.getIdPersona() != null && castOther.getIdPersona() != null && this
				.getIdPersona().equals(castOther.getIdPersona())))
				&& ((this.getIdInculpado() == castOther.getIdInculpado()) || (this
						.getIdInculpado() != null
						&& castOther.getIdInculpado() != null && this
						.getIdInculpado().equals(castOther.getIdInculpado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdPersona() == null ? 0 : this.getIdPersona().hashCode());
		result = 37
				* result
				+ (getIdInculpado() == null ? 0 : this.getIdInculpado()
						.hashCode());
		return result;
	}

}
