package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Instancia generated by hbm2java
 */
public class Instancia implements java.io.Serializable {

	private int idInstancia;
	private Hito hito;
	private String nombre;
	private Set procesos = new HashSet(0);
	private Set hitos = new HashSet(0);

	public Instancia() {
	}

	public Instancia(int idInstancia) {
		this.idInstancia = idInstancia;
	}

	public Instancia(int idInstancia, Hito hito, String nombre, Set procesos,
			Set hitos) {
		this.idInstancia = idInstancia;
		this.hito = hito;
		this.nombre = nombre;
		this.procesos = procesos;
		this.hitos = hitos;
	}

	public int getIdInstancia() {
		return this.idInstancia;
	}

	public void setIdInstancia(int idInstancia) {
		this.idInstancia = idInstancia;
	}

	public Hito getHito() {
		return this.hito;
	}

	public void setHito(Hito hito) {
		this.hito = hito;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProcesos() {
		return this.procesos;
	}

	public void setProcesos(Set procesos) {
		this.procesos = procesos;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

}
