package com.hildebrando.legal.modelo;

// Generated 22-oct-2012 13:27:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina implements java.io.Serializable {

	private int idOficina;
	private Territorio territorio;
	private Ubigeo ubigeo;
	private String nombre;
	private String codigo;
	private Character estado;
	private Set expedientes = new HashSet(0);

	private String nombreDetallado;
	
	public Oficina() {
	}

	public Oficina(int idOficina) {
		this.idOficina = idOficina;
	}

	public Oficina(int idOficina, Territorio territorio, Ubigeo ubigeo,
			String nombre, String codigo, Character estado,Set expedientes) {
		this.idOficina = idOficina;
		this.territorio = territorio;
		this.ubigeo = ubigeo;
		this.nombre = nombre;
		this.codigo = codigo;
		this.expedientes = expedientes;
		this.estado=estado;
	}

	public int getIdOficina() {
		return this.idOficina;
	}

	public void setIdOficina(int idOficina) {
		this.idOficina = idOficina;
	}

	public Territorio getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public String getNombreDetallado() {
		return nombreDetallado;
	}

	public void setNombreDetallado(String nombreDetallado) {
		this.nombreDetallado = nombreDetallado;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}
	
}
