package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Provision generated by hbm2java
 */
public class Provision implements java.io.Serializable {

	private BigDecimal idProvision;
	private Moneda moneda;
	private TipoProvision tipoProvision;
	private Expediente expediente;
	private Serializable fechaSentencia;
	private Serializable fechaProvision;
	private Integer monto;
	private String descripcion;

	public Provision() {
	}

	public Provision(BigDecimal idProvision) {
		this.idProvision = idProvision;
	}

	public Provision(BigDecimal idProvision, Moneda moneda,
			TipoProvision tipoProvision, Expediente expediente,
			Serializable fechaSentencia, Serializable fechaProvision,
			Integer monto, String descripcion) {
		this.idProvision = idProvision;
		this.moneda = moneda;
		this.tipoProvision = tipoProvision;
		this.expediente = expediente;
		this.fechaSentencia = fechaSentencia;
		this.fechaProvision = fechaProvision;
		this.monto = monto;
		this.descripcion = descripcion;
	}

	public BigDecimal getIdProvision() {
		return this.idProvision;
	}

	public void setIdProvision(BigDecimal idProvision) {
		this.idProvision = idProvision;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public TipoProvision getTipoProvision() {
		return this.tipoProvision;
	}

	public void setTipoProvision(TipoProvision tipoProvision) {
		this.tipoProvision = tipoProvision;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Serializable getFechaSentencia() {
		return this.fechaSentencia;
	}

	public void setFechaSentencia(Serializable fechaSentencia) {
		this.fechaSentencia = fechaSentencia;
	}

	public Serializable getFechaProvision() {
		return this.fechaProvision;
	}

	public void setFechaProvision(Serializable fechaProvision) {
		this.fechaProvision = fechaProvision;
	}

	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
