package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Provision generated by hbm2java
 */
public class Provision implements java.io.Serializable {

	private int idProvision;
	private Moneda moneda;
	private TipoProvision tipoProvision;
	private Expediente expediente;
	private Date fechaSentencia;
	private Date fechaProvision;
	private Double monto;
	private String descripcion;

	public Provision() {
	}

	public Provision(int idProvision) {
		this.idProvision = idProvision;
	}

	public Provision(int idProvision, Moneda moneda,
			TipoProvision tipoProvision, Expediente expediente,
			Date fechaSentencia, Date fechaProvision, Double monto,
			String descripcion) {
		this.idProvision = idProvision;
		this.moneda = moneda;
		this.tipoProvision = tipoProvision;
		this.expediente = expediente;
		this.fechaSentencia = fechaSentencia;
		this.fechaProvision = fechaProvision;
		this.monto = monto;
		this.descripcion = descripcion;
	}

	public int getIdProvision() {
		return this.idProvision;
	}

	public void setIdProvision(int idProvision) {
		this.idProvision = idProvision;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public TipoProvision getTipoProvision() {
		return this.tipoProvision;
	}

	public void setTipoProvision(TipoProvision tipoProvision) {
		this.tipoProvision = tipoProvision;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Date getFechaSentencia() {
		return this.fechaSentencia;
	}

	public void setFechaSentencia(Date fechaSentencia) {
		this.fechaSentencia = fechaSentencia;
	}

	public Date getFechaProvision() {
		return this.fechaProvision;
	}

	public void setFechaProvision(Date fechaProvision) {
		this.fechaProvision = fechaProvision;
	}

	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
