package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Riesgo generated by hbm2java
 */
public class Riesgo implements java.io.Serializable {

	private BigDecimal idRiesgo;
	private String descripcion;
	private Set expedientes = new HashSet(0);

	public Riesgo() {
	}

	public Riesgo(BigDecimal idRiesgo) {
		this.idRiesgo = idRiesgo;
	}

	public Riesgo(BigDecimal idRiesgo, String descripcion, Set expedientes) {
		this.idRiesgo = idRiesgo;
		this.descripcion = descripcion;
		this.expedientes = expedientes;
	}

	public BigDecimal getIdRiesgo() {
		return this.idRiesgo;
	}

	public void setIdRiesgo(BigDecimal idRiesgo) {
		this.idRiesgo = idRiesgo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

}
