package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SituacionCuota generated by hbm2java
 */
public class SituacionCuota implements java.io.Serializable {

	private int idSituacionCuota;
	private String descripcion;
	private Set cuotas = new HashSet(0);

	public SituacionCuota() {
	}

	public SituacionCuota(int idSituacionCuota) {
		this.idSituacionCuota = idSituacionCuota;
	}

	public SituacionCuota(int idSituacionCuota, String descripcion, Set cuotas) {
		this.idSituacionCuota = idSituacionCuota;
		this.descripcion = descripcion;
		this.cuotas = cuotas;
	}

	public int getIdSituacionCuota() {
		return this.idSituacionCuota;
	}

	public void setIdSituacionCuota(int idSituacionCuota) {
		this.idSituacionCuota = idSituacionCuota;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

}
