package com.hildebrando.legal.modelo;

// Generated 23-ago-2012 20:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Territorio generated by hbm2java
 */
public class Territorio implements java.io.Serializable {

	private int idTerritorio;
	private GrupoBanca grupoBanca;
	private Integer ubigeo;
	private String provincia;
	private String distrito;
	private String departamento;
	private String codigo;
	private Set oficinas = new HashSet(0);
	private Set organos = new HashSet(0);

	public Territorio() {
	}

	public Territorio(int idTerritorio) {
		this.idTerritorio = idTerritorio;
	}

	public Territorio(int idTerritorio, GrupoBanca grupoBanca, Integer ubigeo,
			String provincia, String distrito, String departamento,
			String codigo, Set oficinas, Set organos) {
		this.idTerritorio = idTerritorio;
		this.grupoBanca = grupoBanca;
		this.ubigeo = ubigeo;
		this.provincia = provincia;
		this.distrito = distrito;
		this.departamento = departamento;
		this.codigo = codigo;
		this.oficinas = oficinas;
		this.organos = organos;
	}

	public int getIdTerritorio() {
		return this.idTerritorio;
	}

	public void setIdTerritorio(int idTerritorio) {
		this.idTerritorio = idTerritorio;
	}

	public GrupoBanca getGrupoBanca() {
		return this.grupoBanca;
	}

	public void setGrupoBanca(GrupoBanca grupoBanca) {
		this.grupoBanca = grupoBanca;
	}

	public Integer getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Integer ubigeo) {
		this.ubigeo = ubigeo;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Set oficinas) {
		this.oficinas = oficinas;
	}

	public Set getOrganos() {
		return this.organos;
	}

	public void setOrganos(Set organos) {
		this.organos = organos;
	}

}
