package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Territorio generated by hbm2java
 */
public class Territorio implements java.io.Serializable {

	private BigDecimal idTerritorio;
	private BigDecimal ubigeo;
	private String provincia;
	private String distrito;
	private String departamento;
	private Set oficinas = new HashSet(0);
	private Set organos = new HashSet(0);
	private Set grupoBancas = new HashSet(0);

	public Territorio() {
	}

	public Territorio(BigDecimal idTerritorio) {
		this.idTerritorio = idTerritorio;
	}

	public Territorio(BigDecimal idTerritorio, BigDecimal ubigeo,
			String provincia, String distrito, String departamento,
			Set oficinas, Set organos, Set grupoBancas) {
		this.idTerritorio = idTerritorio;
		this.ubigeo = ubigeo;
		this.provincia = provincia;
		this.distrito = distrito;
		this.departamento = departamento;
		this.oficinas = oficinas;
		this.organos = organos;
		this.grupoBancas = grupoBancas;
	}

	public BigDecimal getIdTerritorio() {
		return this.idTerritorio;
	}

	public void setIdTerritorio(BigDecimal idTerritorio) {
		this.idTerritorio = idTerritorio;
	}

	public BigDecimal getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(BigDecimal ubigeo) {
		this.ubigeo = ubigeo;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public Set getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Set oficinas) {
		this.oficinas = oficinas;
	}

	public Set getOrganos() {
		return this.organos;
	}

	public void setOrganos(Set organos) {
		this.organos = organos;
	}

	public Set getGrupoBancas() {
		return this.grupoBancas;
	}

	public void setGrupoBancas(Set grupoBancas) {
		this.grupoBancas = grupoBancas;
	}

}
