package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoExpediente generated by hbm2java
 */
public class TipoExpediente implements java.io.Serializable {

	private BigDecimal idTipoExpediente;
	private String nombre;
	private Set expedientes = new HashSet(0);

	public TipoExpediente() {
	}

	public TipoExpediente(BigDecimal idTipoExpediente) {
		this.idTipoExpediente = idTipoExpediente;
	}

	public TipoExpediente(BigDecimal idTipoExpediente, String nombre,
			Set expedientes) {
		this.idTipoExpediente = idTipoExpediente;
		this.nombre = nombre;
		this.expedientes = expedientes;
	}

	public BigDecimal getIdTipoExpediente() {
		return this.idTipoExpediente;
	}

	public void setIdTipoExpediente(BigDecimal idTipoExpediente) {
		this.idTipoExpediente = idTipoExpediente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

}
