package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoHonorario generated by hbm2java
 */
public class TipoHonorario implements java.io.Serializable {

	private BigDecimal idTipoHonorario;
	private String descripcion;
	private Set honorarios = new HashSet(0);

	public TipoHonorario() {
	}

	public TipoHonorario(BigDecimal idTipoHonorario) {
		this.idTipoHonorario = idTipoHonorario;
	}

	public TipoHonorario(BigDecimal idTipoHonorario, String descripcion,
			Set honorarios) {
		this.idTipoHonorario = idTipoHonorario;
		this.descripcion = descripcion;
		this.honorarios = honorarios;
	}

	public BigDecimal getIdTipoHonorario() {
		return this.idTipoHonorario;
	}

	public void setIdTipoHonorario(BigDecimal idTipoHonorario) {
		this.idTipoHonorario = idTipoHonorario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getHonorarios() {
		return this.honorarios;
	}

	public void setHonorarios(Set honorarios) {
		this.honorarios = honorarios;
	}

}
