package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoProvision generated by hbm2java
 */
public class TipoProvision implements java.io.Serializable {

	private int idTipoProvision;
	private String descripcion;
	private Character estado;
	private Set provisions = new HashSet(0);

	public TipoProvision() {
	}

	public TipoProvision(int idTipoProvision) {
		this.idTipoProvision = idTipoProvision;
	}

	public TipoProvision(int idTipoProvision, String descripcion, Set provisions) {
		this.idTipoProvision = idTipoProvision;
		this.descripcion = descripcion;
		this.provisions = provisions;
	}

	public int getIdTipoProvision() {
		return this.idTipoProvision;
	}

	public void setIdTipoProvision(int idTipoProvision) {
		this.idTipoProvision = idTipoProvision;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProvisions() {
		return this.provisions;
	}

	public void setProvisions(Set provisions) {
		this.provisions = provisions;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
