package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Via generated by hbm2java
 */
public class Via implements java.io.Serializable {

	private int idVia;
	private Proceso proceso;
	private String nombre;
	private Set instancias = new HashSet(0);

	public Via() {
	}

	public Via(int idVia) {
		this.idVia = idVia;
	}

	public Via(int idVia, Proceso proceso, String nombre, Set instancias) {
		this.idVia = idVia;
		this.proceso = proceso;
		this.nombre = nombre;
		this.instancias = instancias;
	}

	public int getIdVia() {
		return this.idVia;
	}

	public void setIdVia(int idVia) {
		this.idVia = idVia;
	}

	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getInstancias() {
		return this.instancias;
	}

	public void setInstancias(Set instancias) {
		this.instancias = instancias;
	}

}
