package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Abogado generated by hbm2java
 */
public class Abogado implements java.io.Serializable {

	private int idAbogado;
	private String registroca;
	private Integer dni;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String telefono;
	private String correo;
	private String nombreCompleto;
	private Set abogadoEstudios = new HashSet(0);
	private Set honorarios = new HashSet(0);

	private String nombreCompletoMayuscula;
	
	public Abogado() {
	}

	public Abogado(int idAbogado) {
		this.idAbogado = idAbogado;
	}

	public Abogado(int idAbogado, String registroca, Integer dni,
			String nombres, String apellidoPaterno, String apellidoMaterno,
			String telefono, String correo, String nombreCompleto,
			Set abogadoEstudios, Set honorarios) {
		this.idAbogado = idAbogado;
		this.registroca = registroca;
		this.dni = dni;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.telefono = telefono;
		this.correo = correo;
		this.nombreCompleto = nombreCompleto;
		this.abogadoEstudios = abogadoEstudios;
		this.honorarios = honorarios;
	}

	public int getIdAbogado() {
		return this.idAbogado;
	}

	public void setIdAbogado(int idAbogado) {
		this.idAbogado = idAbogado;
	}

	public String getRegistroca() {
		return this.registroca;
	}

	public void setRegistroca(String registroca) {
		this.registroca = registroca;
	}

	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public Set getAbogadoEstudios() {
		return this.abogadoEstudios;
	}

	public void setAbogadoEstudios(Set abogadoEstudios) {
		this.abogadoEstudios = abogadoEstudios;
	}

	public Set getHonorarios() {
		return this.honorarios;
	}

	public void setHonorarios(Set honorarios) {
		this.honorarios = honorarios;
	}

	public String getNombreCompletoMayuscula() {
		return nombreCompletoMayuscula;
	}

	public void setNombreCompletoMayuscula(String nombreCompletoMayuscula) {
		this.nombreCompletoMayuscula = nombreCompletoMayuscula;
	}

}
