package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	private BigDecimal idActividad;
	private String nombre;
	private Set actividadProcesals = new HashSet(0);

	public Actividad() {
	}

	public Actividad(BigDecimal idActividad) {
		this.idActividad = idActividad;
	}

	public Actividad(BigDecimal idActividad, String nombre,
			Set actividadProcesals) {
		this.idActividad = idActividad;
		this.nombre = nombre;
		this.actividadProcesals = actividadProcesals;
	}

	public BigDecimal getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(BigDecimal idActividad) {
		this.idActividad = idActividad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getActividadProcesals() {
		return this.actividadProcesals;
	}

	public void setActividadProcesals(Set actividadProcesals) {
		this.actividadProcesals = actividadProcesals;
	}

}
