package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Anexo generated by hbm2java
 */
public class Anexo implements java.io.Serializable {

	private int idDocumento;
	private Expediente expediente;
	private String titulo;
	private String comentario;
	private Date fechaInicio;
	private String referencia;

	public Anexo() {
	}

	public Anexo(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	public Anexo(int idDocumento, Expediente expediente, String titulo,
			String comentario, Date fechaInicio, String referencia) {
		this.idDocumento = idDocumento;
		this.expediente = expediente;
		this.titulo = titulo;
		this.comentario = comentario;
		this.fechaInicio = fechaInicio;
		this.referencia = referencia;
	}

	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

}
