package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion implements java.io.Serializable {

	private int idCalificacion;
	private String nombre;
	private Character estado;
	private Set expedientes = new HashSet(0);

	public Calificacion() {
	}

	public Calificacion(int idCalificacion) {
		this.idCalificacion = idCalificacion;
	}

	public Calificacion(int idCalificacion, String nombre, Set expedientes) {
		this.idCalificacion = idCalificacion;
		this.nombre = nombre;
		this.expedientes = expedientes;
	}

	public int getIdCalificacion() {
		return this.idCalificacion;
	}

	public void setIdCalificacion(int idCalificacion) {
		this.idCalificacion = idCalificacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}
}
