package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;

/**
 * Correo generated by hbm2java
 */
public class Correo implements java.io.Serializable {

	private int idCorreo;
	private String from;
	private String to;
	private String cc;
	private String co;
	private String asunto;
	private Clob contenido;

	public Correo() {
	}

	public Correo(int idCorreo) {
		this.idCorreo = idCorreo;
	}

	public Correo(int idCorreo, String from, String to, String cc, String co,
			String asunto, Clob contenido) {
		this.idCorreo = idCorreo;
		this.from = from;
		this.to = to;
		this.cc = cc;
		this.co = co;
		this.asunto = asunto;
		this.contenido = contenido;
	}

	public int getIdCorreo() {
		return this.idCorreo;
	}

	public void setIdCorreo(int idCorreo) {
		this.idCorreo = idCorreo;
	}

	public String getFrom() {
		return this.from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getTo() {
		return this.to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

	public String getCo() {
		return this.co;
	}

	public void setCo(String co) {
		this.co = co;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public Clob getContenido() {
		return this.contenido;
	}

	public void setContenido(Clob contenido) {
		this.contenido = contenido;
	}

}
