package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

/**
 * Cuantia generated by hbm2java
 */
public class Cuantia implements java.io.Serializable {

	private int idCuantia;
	private Moneda moneda;
	private Materia materia;
	private Expediente expediente;
	private Double pretendido;

	
	
	public Cuantia(Moneda moneda, Materia materia) {
		super();
		this.moneda = moneda;
		this.materia = materia;
	}

	public Cuantia() {
	}

	public Cuantia(int idCuantia) {
		this.idCuantia = idCuantia;
	}

	public Cuantia(int idCuantia, Moneda moneda, Materia materia,
			Expediente expediente, Double pretendido) {
		this.idCuantia = idCuantia;
		this.moneda = moneda;
		this.materia = materia;
		this.expediente = expediente;
		this.pretendido = pretendido;
	}

	public int getIdCuantia() {
		return this.idCuantia;
	}

	public void setIdCuantia(int idCuantia) {
		this.idCuantia = idCuantia;
	}

	public Moneda getMoneda() {
		if(moneda==null)
			moneda = new Moneda();
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Double getPretendido() {
		return this.pretendido;
	}

	public void setPretendido(Double pretendido) {
		this.pretendido = pretendido;
	}

}
