package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private BigDecimal idCuota;
	private Honorario honorario;
	private SituacionCuota situacionCuota;
	private String numero;
	private BigDecimal nroRecibo;
	private Integer importe;
	private Serializable fechaPago;

	public Cuota() {
	}

	public Cuota(BigDecimal idCuota) {
		this.idCuota = idCuota;
	}

	public Cuota(BigDecimal idCuota, Honorario honorario,
			SituacionCuota situacionCuota, String numero, BigDecimal nroRecibo,
			Integer importe, Serializable fechaPago) {
		this.idCuota = idCuota;
		this.honorario = honorario;
		this.situacionCuota = situacionCuota;
		this.numero = numero;
		this.nroRecibo = nroRecibo;
		this.importe = importe;
		this.fechaPago = fechaPago;
	}

	public BigDecimal getIdCuota() {
		return this.idCuota;
	}

	public void setIdCuota(BigDecimal idCuota) {
		this.idCuota = idCuota;
	}

	public Honorario getHonorario() {
		return this.honorario;
	}

	public void setHonorario(Honorario honorario) {
		this.honorario = honorario;
	}

	public SituacionCuota getSituacionCuota() {
		return this.situacionCuota;
	}

	public void setSituacionCuota(SituacionCuota situacionCuota) {
		this.situacionCuota = situacionCuota;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public BigDecimal getNroRecibo() {
		return this.nroRecibo;
	}

	public void setNroRecibo(BigDecimal nroRecibo) {
		this.nroRecibo = nroRecibo;
	}

	public Integer getImporte() {
		return this.importe;
	}

	public void setImporte(Integer importe) {
		this.importe = importe;
	}

	public Serializable getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Serializable fechaPago) {
		this.fechaPago = fechaPago;
	}

}
