package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

/**
 * DependeDe generated by hbm2java
 */
public class DependeDe implements java.io.Serializable {

	private DependeDeId id;

	public DependeDe() {
	}

	public DependeDe(DependeDeId id) {
		this.id = id;
	}

	public DependeDeId getId() {
		return this.id;
	}

	public void setId(DependeDeId id) {
		this.id = id;
	}

}
