package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Documento generated by hbm2java
 */
public class Documento implements java.io.Serializable {

	private int idDocumento;
	private Hito hito;
	private String titulo;
	private String comentario;
	private Date fechaInicio;
	private String referencia;

	public Documento() {
	}

	public Documento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	public Documento(int idDocumento, Hito hito, String titulo,
			String comentario, Date fechaInicio, String referencia) {
		this.idDocumento = idDocumento;
		this.hito = hito;
		this.titulo = titulo;
		this.comentario = comentario;
		this.fechaInicio = fechaInicio;
		this.referencia = referencia;
	}

	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	public Hito getHito() {
		return this.hito;
	}

	public void setHito(Hito hito) {
		this.hito = hito;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

}
