package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Entidad generated by hbm2java
 */
public class Entidad implements java.io.Serializable {

	private BigDecimal idEntidad;
	private String nombre;
	private Set organos = new HashSet(0);

	public Entidad() {
	}

	public Entidad(BigDecimal idEntidad) {
		this.idEntidad = idEntidad;
	}

	public Entidad(BigDecimal idEntidad, String nombre, Set organos) {
		this.idEntidad = idEntidad;
		this.nombre = nombre;
		this.organos = organos;
	}

	public BigDecimal getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(BigDecimal idEntidad) {
		this.idEntidad = idEntidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getOrganos() {
		return this.organos;
	}

	public void setOrganos(Set organos) {
		this.organos = organos;
	}

}
