package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EstadoExpediente generated by hbm2java
 */
public class EstadoExpediente implements java.io.Serializable {

	private BigDecimal idEstadoExpediente;
	private String nombre;
	private Set expedientes = new HashSet(0);

	public EstadoExpediente() {
	}

	public EstadoExpediente(BigDecimal idEstadoExpediente) {
		this.idEstadoExpediente = idEstadoExpediente;
	}

	public EstadoExpediente(BigDecimal idEstadoExpediente, String nombre,
			Set expedientes) {
		this.idEstadoExpediente = idEstadoExpediente;
		this.nombre = nombre;
		this.expedientes = expedientes;
	}

	public BigDecimal getIdEstadoExpediente() {
		return this.idEstadoExpediente;
	}

	public void setIdEstadoExpediente(BigDecimal idEstadoExpediente) {
		this.idEstadoExpediente = idEstadoExpediente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

}
