package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Estudio generated by hbm2java
 */
public class Estudio implements java.io.Serializable {

	private int idEstudio;
	private Long ruc;
	private String direccion;
	private String telefono;
	private String correo;
	private String nombre;
	private String fax;
	private Set abogados = new HashSet(0);

	public Estudio() {
	}

	public Estudio(int idEstudio) {
		this.idEstudio = idEstudio;
	}

	public Estudio(int idEstudio, Long ruc, String direccion, String telefono,
			String correo, String nombre, String fax, Set abogados) {
		this.idEstudio = idEstudio;
		this.ruc = ruc;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.nombre = nombre;
		this.fax = fax;
		this.abogados = abogados;
	}

	public int getIdEstudio() {
		return this.idEstudio;
	}

	public void setIdEstudio(int idEstudio) {
		this.idEstudio = idEstudio;
	}

	public Long getRuc() {
		return this.ruc;
	}

	public void setRuc(Long ruc) {
		this.ruc = ruc;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Set getAbogados() {
		return this.abogados;
	}

	public void setAbogados(Set abogados) {
		this.abogados = abogados;
	}

}
