package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudio generated by hbm2java
 */
public class Estudio implements java.io.Serializable {

	private BigDecimal idEstudio;
	private BigDecimal ruc;
	private String direccion;
	private BigDecimal telefono;
	private String correo;
	private Set abogados = new HashSet(0);

	public Estudio() {
	}

	public Estudio(BigDecimal idEstudio) {
		this.idEstudio = idEstudio;
	}

	public Estudio(BigDecimal idEstudio, BigDecimal ruc, String direccion,
			BigDecimal telefono, String correo, Set abogados) {
		this.idEstudio = idEstudio;
		this.ruc = ruc;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.abogados = abogados;
	}

	public BigDecimal getIdEstudio() {
		return this.idEstudio;
	}

	public void setIdEstudio(BigDecimal idEstudio) {
		this.idEstudio = idEstudio;
	}

	public BigDecimal getRuc() {
		return this.ruc;
	}

	public void setRuc(BigDecimal ruc) {
		this.ruc = ruc;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public BigDecimal getTelefono() {
		return this.telefono;
	}

	public void setTelefono(BigDecimal telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Set getAbogados() {
		return this.abogados;
	}

	public void setAbogados(Set abogados) {
		this.abogados = abogados;
	}

}
