package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente implements java.io.Serializable {

	private long idExpediente;
	private TipoExpediente tipoExpediente;
	private ContraCautela contraCautela;
	private EstadoCautelar estadoCautelar;
	private EstadoExpediente estadoExpediente;
	private Usuario usuario;
	private TipoCautelar tipoCautelar;
	private Recurrencia recurrencia;
	private Oficina oficina;
	private Instancia instancia;
	private Moneda moneda;
	private Organo organo;
	private Calificacion calificacion;
	private Riesgo riesgo;
	private String numeroExpediente;
	private Date fechaInicioProceso;
	private Date fechaResumen;
	private String textoResumen;
	private Clob acumuladoResumen;
	private Date fechaFinProceso;
	private Double montoCautelar;
	private String descripcionCautelar;
	private Double importeCautelar;
	private String secretario;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private List<Involucrado> involucrados;
	private List<Honorario> honorarios;
	private List<Cuantia> cuantias;
	private List<Inculpado> inculpados;
	private List<Anexo> anexos;
	private List<Hito> hitos;
	private List<Provision> provisions;

	public Expediente() {
	}

	public Expediente(long idExpediente) {
		this.idExpediente = idExpediente;
	}

	public Expediente(long idExpediente, TipoExpediente tipoExpediente,
			ContraCautela contraCautela, EstadoCautelar estadoCautelar,
			EstadoExpediente estadoExpediente, Usuario usuario,
			TipoCautelar tipoCautelar, Recurrencia recurrencia,
			Oficina oficina, Instancia instancia, Moneda moneda, Organo organo,
			Calificacion calificacion, Riesgo riesgo, String numeroExpediente,
			Date fechaInicioProceso, Date fechaResumen, String textoResumen,
			Clob acumuladoResumen, Date fechaFinProceso, Double montoCautelar,
			String descripcionCautelar, Double importeCautelar,
			String secretario, Date fechaCreacion, Date fechaModificacion,
			String usuarioCreacion, String usuarioModificacion,
			List involucrados, List honorarios, List cuantias, List inculpados,
			List anexos, List hitos, List provisions) {
		this.idExpediente = idExpediente;
		this.tipoExpediente = tipoExpediente;
		this.contraCautela = contraCautela;
		this.estadoCautelar = estadoCautelar;
		this.estadoExpediente = estadoExpediente;
		this.usuario = usuario;
		this.tipoCautelar = tipoCautelar;
		this.recurrencia = recurrencia;
		this.oficina = oficina;
		this.instancia = instancia;
		this.moneda = moneda;
		this.organo = organo;
		this.calificacion = calificacion;
		this.riesgo = riesgo;
		this.numeroExpediente = numeroExpediente;
		this.fechaInicioProceso = fechaInicioProceso;
		this.fechaResumen = fechaResumen;
		this.textoResumen = textoResumen;
		this.acumuladoResumen = acumuladoResumen;
		this.fechaFinProceso = fechaFinProceso;
		this.montoCautelar = montoCautelar;
		this.descripcionCautelar = descripcionCautelar;
		this.importeCautelar = importeCautelar;
		this.secretario = secretario;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.involucrados = involucrados;
		this.honorarios = honorarios;
		this.cuantias = cuantias;
		this.inculpados = inculpados;
		this.anexos = anexos;
		this.hitos = hitos;
		this.provisions = provisions;
	}

	public long getIdExpediente() {
		return this.idExpediente;
	}

	public void setIdExpediente(long idExpediente) {
		this.idExpediente = idExpediente;
	}

	public TipoExpediente getTipoExpediente() {
		return this.tipoExpediente;
	}

	public void setTipoExpediente(TipoExpediente tipoExpediente) {
		this.tipoExpediente = tipoExpediente;
	}

	public ContraCautela getContraCautela() {
		return this.contraCautela;
	}

	public void setContraCautela(ContraCautela contraCautela) {
		this.contraCautela = contraCautela;
	}

	public EstadoCautelar getEstadoCautelar() {
		return this.estadoCautelar;
	}

	public void setEstadoCautelar(EstadoCautelar estadoCautelar) {
		this.estadoCautelar = estadoCautelar;
	}

	public EstadoExpediente getEstadoExpediente() {
		return this.estadoExpediente;
	}

	public void setEstadoExpediente(EstadoExpediente estadoExpediente) {
		this.estadoExpediente = estadoExpediente;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public TipoCautelar getTipoCautelar() {
		return this.tipoCautelar;
	}

	public void setTipoCautelar(TipoCautelar tipoCautelar) {
		this.tipoCautelar = tipoCautelar;
	}

	public Recurrencia getRecurrencia() {
		return this.recurrencia;
	}

	public void setRecurrencia(Recurrencia recurrencia) {
		this.recurrencia = recurrencia;
	}

	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	public Instancia getInstancia() {
		return this.instancia;
	}

	public void setInstancia(Instancia instancia) {
		this.instancia = instancia;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public Organo getOrgano() {
		return this.organo;
	}

	public void setOrgano(Organo organo) {
		this.organo = organo;
	}

	public Calificacion getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Calificacion calificacion) {
		this.calificacion = calificacion;
	}

	public Riesgo getRiesgo() {
		return this.riesgo;
	}

	public void setRiesgo(Riesgo riesgo) {
		this.riesgo = riesgo;
	}

	public String getNumeroExpediente() {
		return this.numeroExpediente;
	}

	public void setNumeroExpediente(String numeroExpediente) {
		this.numeroExpediente = numeroExpediente;
	}

	public Date getFechaInicioProceso() {
		return this.fechaInicioProceso;
	}

	public void setFechaInicioProceso(Date fechaInicioProceso) {
		this.fechaInicioProceso = fechaInicioProceso;
	}

	public Date getFechaResumen() {
		return this.fechaResumen;
	}

	public void setFechaResumen(Date fechaResumen) {
		this.fechaResumen = fechaResumen;
	}

	public String getTextoResumen() {
		return this.textoResumen;
	}

	public void setTextoResumen(String textoResumen) {
		this.textoResumen = textoResumen;
	}

	public Clob getAcumuladoResumen() {
		return this.acumuladoResumen;
	}

	public void setAcumuladoResumen(Clob acumuladoResumen) {
		this.acumuladoResumen = acumuladoResumen;
	}

	public Date getFechaFinProceso() {
		return this.fechaFinProceso;
	}

	public void setFechaFinProceso(Date fechaFinProceso) {
		this.fechaFinProceso = fechaFinProceso;
	}

	

	public String getDescripcionCautelar() {
		return this.descripcionCautelar;
	}

	public void setDescripcionCautelar(String descripcionCautelar) {
		this.descripcionCautelar = descripcionCautelar;
	}

	public Double getImporteCautelar() {
		return this.importeCautelar;
	}

	public void setImporteCautelar(Double importeCautelar) {
		this.importeCautelar = importeCautelar;
	}

	public String getSecretario() {
		return this.secretario;
	}

	public void setSecretario(String secretario) {
		this.secretario = secretario;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public List<Involucrado> getInvolucrados() {
		if(involucrados == null)
			involucrados = new ArrayList<Involucrado>();
		return involucrados;
	}

	public void setInvolucrados(List<Involucrado> involucrados) {
		this.involucrados = involucrados;
	}

	public List<Honorario> getHonorarios() {
		if(honorarios == null)
			honorarios = new ArrayList<Honorario>();
		return honorarios;
	}

	public void setHonorarios(List<Honorario> honorarios) {
		this.honorarios = honorarios;
	}

	public List<Cuantia> getCuantias() {
		if(cuantias == null)
			cuantias = new ArrayList<Cuantia>();
		return cuantias;
	}

	public void setCuantias(List<Cuantia> cuantias) {
		this.cuantias = cuantias;
	}

	public List<Inculpado> getInculpados() {
		if(inculpados == null)
			inculpados = new ArrayList<Inculpado>();
		return inculpados;
	}

	public void setInculpados(List<Inculpado> inculpados) {
		this.inculpados = inculpados;
	}

	public List<Anexo> getAnexos() {
		if(anexos == null)
			anexos = new ArrayList<Anexo>();
		return anexos;
	}

	public void setAnexos(List<Anexo> anexos) {
		this.anexos = anexos;
	}

	public List<Hito> getHitos() {
		if(hitos == null)
			hitos = new ArrayList<Hito>();
		return hitos;
	}

	public void setHitos(List<Hito> hitos) {
		this.hitos = hitos;
	}

	public List<Provision> getProvisions() {
		if(provisions == null)
			provisions = new ArrayList<Provision>();
		return provisions;
	}

	public void setProvisions(List<Provision> provisions) {
		this.provisions = provisions;
	}

	public Double getMontoCautelar() {
		return montoCautelar;
	}

	public void setMontoCautelar(Double montoCautelar) {
		this.montoCautelar = montoCautelar;
	}


}
