package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente implements java.io.Serializable {

	private long idExpediente;
	private TipoExpediente tipoExpediente;
	private ContraCautela contraCautela;
	private EstadoCautelar estadoCautelar;
	private Moneda moneda;
	private EstadoExpediente estadoExpediente;
	private Usuario usuario;
	private Responsable responsable;
	private TipoCautelar tipoCautelar;
	private Calificacion calificacion;
	private Riesgo riesgo;
	private Recurrencia recurrencia;
	private Integer numero;
	private Date fechaInicioProceso;
	private Date fechaResumen;
	private String textoResumen;
	private Clob acumuladoResumen;
	private Date fechaFinProceso;
	private Integer montoCautelar;
	private String descripcionCautelar;
	private Double importeCautelar;
	private String secretario;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private Set involucrados = new HashSet(0);
	private Set honorarios = new HashSet(0);
	private Set cuantias = new HashSet(0);
	private Set inculpados = new HashSet(0);
	private Set hitos = new HashSet(0);
	private Set provisions = new HashSet(0);

	public Expediente() {
	}

	public Expediente(long idExpediente) {
		this.idExpediente = idExpediente;
	}

	public Expediente(long idExpediente, TipoExpediente tipoExpediente,
			ContraCautela contraCautela, EstadoCautelar estadoCautelar,
			Moneda moneda, EstadoExpediente estadoExpediente, Usuario usuario,
			Responsable responsable, TipoCautelar tipoCautelar,
			Calificacion calificacion, Riesgo riesgo, Recurrencia recurrencia,
			Integer numero, Date fechaInicioProceso, Date fechaResumen,
			String textoResumen, Clob acumuladoResumen, Date fechaFinProceso,
			Integer montoCautelar, String descripcionCautelar,
			Double importeCautelar, String secretario, Date fechaCreacion,
			Date fechaModificacion, String usuarioCreacion,
			String usuarioModificacion, Set involucrados, Set honorarios,
			Set cuantias, Set inculpados, Set hitos, Set provisions) {
		this.idExpediente = idExpediente;
		this.tipoExpediente = tipoExpediente;
		this.contraCautela = contraCautela;
		this.estadoCautelar = estadoCautelar;
		this.moneda = moneda;
		this.estadoExpediente = estadoExpediente;
		this.usuario = usuario;
		this.responsable = responsable;
		this.tipoCautelar = tipoCautelar;
		this.calificacion = calificacion;
		this.riesgo = riesgo;
		this.recurrencia = recurrencia;
		this.numero = numero;
		this.fechaInicioProceso = fechaInicioProceso;
		this.fechaResumen = fechaResumen;
		this.textoResumen = textoResumen;
		this.acumuladoResumen = acumuladoResumen;
		this.fechaFinProceso = fechaFinProceso;
		this.montoCautelar = montoCautelar;
		this.descripcionCautelar = descripcionCautelar;
		this.importeCautelar = importeCautelar;
		this.secretario = secretario;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.involucrados = involucrados;
		this.honorarios = honorarios;
		this.cuantias = cuantias;
		this.inculpados = inculpados;
		this.hitos = hitos;
		this.provisions = provisions;
	}

	public long getIdExpediente() {
		return this.idExpediente;
	}

	public void setIdExpediente(long idExpediente) {
		this.idExpediente = idExpediente;
	}

	public TipoExpediente getTipoExpediente() {
		return this.tipoExpediente;
	}

	public void setTipoExpediente(TipoExpediente tipoExpediente) {
		this.tipoExpediente = tipoExpediente;
	}

	public ContraCautela getContraCautela() {
		return this.contraCautela;
	}

	public void setContraCautela(ContraCautela contraCautela) {
		this.contraCautela = contraCautela;
	}

	public EstadoCautelar getEstadoCautelar() {
		return this.estadoCautelar;
	}

	public void setEstadoCautelar(EstadoCautelar estadoCautelar) {
		this.estadoCautelar = estadoCautelar;
	}

	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	public EstadoExpediente getEstadoExpediente() {
		return this.estadoExpediente;
	}

	public void setEstadoExpediente(EstadoExpediente estadoExpediente) {
		this.estadoExpediente = estadoExpediente;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Responsable getResponsable() {
		return this.responsable;
	}

	public void setResponsable(Responsable responsable) {
		this.responsable = responsable;
	}

	public TipoCautelar getTipoCautelar() {
		return this.tipoCautelar;
	}

	public void setTipoCautelar(TipoCautelar tipoCautelar) {
		this.tipoCautelar = tipoCautelar;
	}

	public Calificacion getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Calificacion calificacion) {
		this.calificacion = calificacion;
	}

	public Riesgo getRiesgo() {
		return this.riesgo;
	}

	public void setRiesgo(Riesgo riesgo) {
		this.riesgo = riesgo;
	}

	public Recurrencia getRecurrencia() {
		return this.recurrencia;
	}

	public void setRecurrencia(Recurrencia recurrencia) {
		this.recurrencia = recurrencia;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Date getFechaInicioProceso() {
		return this.fechaInicioProceso;
	}

	public void setFechaInicioProceso(Date fechaInicioProceso) {
		this.fechaInicioProceso = fechaInicioProceso;
	}

	public Date getFechaResumen() {
		return this.fechaResumen;
	}

	public void setFechaResumen(Date fechaResumen) {
		this.fechaResumen = fechaResumen;
	}

	public String getTextoResumen() {
		return this.textoResumen;
	}

	public void setTextoResumen(String textoResumen) {
		this.textoResumen = textoResumen;
	}

	public Clob getAcumuladoResumen() {
		return this.acumuladoResumen;
	}

	public void setAcumuladoResumen(Clob acumuladoResumen) {
		this.acumuladoResumen = acumuladoResumen;
	}

	public Date getFechaFinProceso() {
		return this.fechaFinProceso;
	}

	public void setFechaFinProceso(Date fechaFinProceso) {
		this.fechaFinProceso = fechaFinProceso;
	}

	public Integer getMontoCautelar() {
		return this.montoCautelar;
	}

	public void setMontoCautelar(Integer montoCautelar) {
		this.montoCautelar = montoCautelar;
	}

	public String getDescripcionCautelar() {
		return this.descripcionCautelar;
	}

	public void setDescripcionCautelar(String descripcionCautelar) {
		this.descripcionCautelar = descripcionCautelar;
	}

	public Double getImporteCautelar() {
		return this.importeCautelar;
	}

	public void setImporteCautelar(Double importeCautelar) {
		this.importeCautelar = importeCautelar;
	}

	public String getSecretario() {
		return this.secretario;
	}

	public void setSecretario(String secretario) {
		this.secretario = secretario;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Set getInvolucrados() {
		return this.involucrados;
	}

	public void setInvolucrados(Set involucrados) {
		this.involucrados = involucrados;
	}

	public Set getHonorarios() {
		return this.honorarios;
	}

	public void setHonorarios(Set honorarios) {
		this.honorarios = honorarios;
	}

	public Set getCuantias() {
		return this.cuantias;
	}

	public void setCuantias(Set cuantias) {
		this.cuantias = cuantias;
	}

	public Set getInculpados() {
		return this.inculpados;
	}

	public void setInculpados(Set inculpados) {
		this.inculpados = inculpados;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

	public Set getProvisions() {
		return this.provisions;
	}

	public void setProvisions(Set provisions) {
		this.provisions = provisions;
	}

}
