package com.hildebrando.legal.modelo;

// Generated 23-ago-2012 20:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Hito generated by hbm2java
 */
public class Hito implements java.io.Serializable {

	private long idHito;
	private Hito hito;
	private FormaConclusion formaConclusion;
	private Expediente expediente;
	private String comentario;
	private Character flagRevertir;
	private Set hitos = new HashSet(0);
	private List<ActividadProcesal> actividadProcesals;

	public Hito() {
	}

	public Hito(long idHito) {
		this.idHito = idHito;
	}

	public Hito(long idHito, Hito hito, FormaConclusion formaConclusion,
			Expediente expediente, String comentario, Character flagRevertir,
			Set hitos, List actividadProcesals) {
		this.idHito = idHito;
		this.hito = hito;
		this.formaConclusion = formaConclusion;
		this.expediente = expediente;
		this.comentario = comentario;
		this.flagRevertir = flagRevertir;
		this.hitos = hitos;
		this.actividadProcesals = actividadProcesals;
	}

	public long getIdHito() {
		return this.idHito;
	}

	public void setIdHito(long idHito) {
		this.idHito = idHito;
	}

	public Hito getHito() {
		return this.hito;
	}

	public void setHito(Hito hito) {
		this.hito = hito;
	}

	public FormaConclusion getFormaConclusion() {
		return this.formaConclusion;
	}

	public void setFormaConclusion(FormaConclusion formaConclusion) {
		this.formaConclusion = formaConclusion;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Character getFlagRevertir() {
		return this.flagRevertir;
	}

	public void setFlagRevertir(Character flagRevertir) {
		this.flagRevertir = flagRevertir;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

	public List<ActividadProcesal> getActividadProcesals() {
		return actividadProcesals;
	}

	public void setActividadProcesals(List<ActividadProcesal> actividadProcesals) {
		this.actividadProcesals = actividadProcesals;
	}
	
	public void agregarActividadProcesal(ActividadProcesal actividadProcesal){
		actividadProcesal.setHito(this);
		actividadProcesals.add(actividadProcesal);
	}

	
}
