package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Hito generated by hbm2java
 */
public class Hito implements java.io.Serializable {

	private BigDecimal idHito;
	private Hito hito;
	private Oficina oficina;
	private FormaConclusion formaConclusion;
	private Instancia instancia;
	private Organo organo;
	private Expediente expediente;
	private Serializable fechaInicio;
	private Serializable fechaFin;
	private String comentario;
	private Character flagRevertir;
	private Set hitos = new HashSet(0);
	private Set documentos = new HashSet(0);
	private Set instancias = new HashSet(0);
	private Set actividadProcesals = new HashSet(0);

	public Hito() {
	}

	public Hito(BigDecimal idHito) {
		this.idHito = idHito;
	}

	public Hito(BigDecimal idHito, Hito hito, Oficina oficina,
			FormaConclusion formaConclusion, Instancia instancia,
			Organo organo, Expediente expediente, Serializable fechaInicio,
			Serializable fechaFin, String comentario, Character flagRevertir,
			Set hitos, Set documentos, Set instancias, Set actividadProcesals) {
		this.idHito = idHito;
		this.hito = hito;
		this.oficina = oficina;
		this.formaConclusion = formaConclusion;
		this.instancia = instancia;
		this.organo = organo;
		this.expediente = expediente;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.comentario = comentario;
		this.flagRevertir = flagRevertir;
		this.hitos = hitos;
		this.documentos = documentos;
		this.instancias = instancias;
		this.actividadProcesals = actividadProcesals;
	}

	public BigDecimal getIdHito() {
		return this.idHito;
	}

	public void setIdHito(BigDecimal idHito) {
		this.idHito = idHito;
	}

	public Hito getHito() {
		return this.hito;
	}

	public void setHito(Hito hito) {
		this.hito = hito;
	}

	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	public FormaConclusion getFormaConclusion() {
		return this.formaConclusion;
	}

	public void setFormaConclusion(FormaConclusion formaConclusion) {
		this.formaConclusion = formaConclusion;
	}

	public Instancia getInstancia() {
		return this.instancia;
	}

	public void setInstancia(Instancia instancia) {
		this.instancia = instancia;
	}

	public Organo getOrgano() {
		return this.organo;
	}

	public void setOrgano(Organo organo) {
		this.organo = organo;
	}

	public Expediente getExpediente() {
		return this.expediente;
	}

	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
	}

	public Serializable getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Serializable fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Serializable getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Serializable fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Character getFlagRevertir() {
		return this.flagRevertir;
	}

	public void setFlagRevertir(Character flagRevertir) {
		this.flagRevertir = flagRevertir;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

	public Set getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set documentos) {
		this.documentos = documentos;
	}

	public Set getInstancias() {
		return this.instancias;
	}

	public void setInstancias(Set instancias) {
		this.instancias = instancias;
	}

	public Set getActividadProcesals() {
		return this.actividadProcesals;
	}

	public void setActividadProcesals(Set actividadProcesals) {
		this.actividadProcesals = actividadProcesals;
	}

}
