package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Instancia generated by hbm2java
 */
public class Instancia implements java.io.Serializable {

	private int idInstancia;
	private String nombre;
	private Set hitos = new HashSet(0);

	public Instancia() {
	}

	public Instancia(int idInstancia) {
		this.idInstancia = idInstancia;
	}

	public Instancia(int idInstancia, String nombre, Set hitos) {
		this.idInstancia = idInstancia;
		this.nombre = nombre;
		this.hitos = hitos;
	}

	public int getIdInstancia() {
		return this.idInstancia;
	}

	public void setIdInstancia(int idInstancia) {
		this.idInstancia = idInstancia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

}
