package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Instancia generated by hbm2java
 */
public class Instancia implements java.io.Serializable {

	private BigDecimal idInstancia;
	private Hito hito;
	private String nombre;
	private Set procesos = new HashSet(0);
	private Set hitos = new HashSet(0);

	public Instancia() {
	}

	public Instancia(BigDecimal idInstancia) {
		this.idInstancia = idInstancia;
	}

	public Instancia(BigDecimal idInstancia, Hito hito, String nombre,
			Set procesos, Set hitos) {
		this.idInstancia = idInstancia;
		this.hito = hito;
		this.nombre = nombre;
		this.procesos = procesos;
		this.hitos = hitos;
	}

	public BigDecimal getIdInstancia() {
		return this.idInstancia;
	}

	public void setIdInstancia(BigDecimal idInstancia) {
		this.idInstancia = idInstancia;
	}

	public Hito getHito() {
		return this.hito;
	}

	public void setHito(Hito hito) {
		this.hito = hito;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProcesos() {
		return this.procesos;
	}

	public void setProcesos(Set procesos) {
		this.procesos = procesos;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

}
