package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * InvolucradoId generated by hbm2java
 */
public class InvolucradoId implements java.io.Serializable {

	private BigDecimal idPersona;
	private BigDecimal idInvolucrado;

	public InvolucradoId() {
	}

	public InvolucradoId(BigDecimal idPersona, BigDecimal idInvolucrado) {
		this.idPersona = idPersona;
		this.idInvolucrado = idInvolucrado;
	}

	public BigDecimal getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(BigDecimal idPersona) {
		this.idPersona = idPersona;
	}

	public BigDecimal getIdInvolucrado() {
		return this.idInvolucrado;
	}

	public void setIdInvolucrado(BigDecimal idInvolucrado) {
		this.idInvolucrado = idInvolucrado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvolucradoId))
			return false;
		InvolucradoId castOther = (InvolucradoId) other;

		return ((this.getIdPersona() == castOther.getIdPersona()) || (this
				.getIdPersona() != null && castOther.getIdPersona() != null && this
				.getIdPersona().equals(castOther.getIdPersona())))
				&& ((this.getIdInvolucrado() == castOther.getIdInvolucrado()) || (this
						.getIdInvolucrado() != null
						&& castOther.getIdInvolucrado() != null && this
						.getIdInvolucrado()
						.equals(castOther.getIdInvolucrado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdPersona() == null ? 0 : this.getIdPersona().hashCode());
		result = 37
				* result
				+ (getIdInvolucrado() == null ? 0 : this.getIdInvolucrado()
						.hashCode());
		return result;
	}

}
