package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina implements java.io.Serializable {

	private BigDecimal idOficina;
	private Territorio territorio;
	private String nombre;
	private Set hitos = new HashSet(0);

	public Oficina() {
	}

	public Oficina(BigDecimal idOficina) {
		this.idOficina = idOficina;
	}

	public Oficina(BigDecimal idOficina, Territorio territorio, String nombre,
			Set hitos) {
		this.idOficina = idOficina;
		this.territorio = territorio;
		this.nombre = nombre;
		this.hitos = hitos;
	}

	public BigDecimal getIdOficina() {
		return this.idOficina;
	}

	public void setIdOficina(BigDecimal idOficina) {
		this.idOficina = idOficina;
	}

	public Territorio getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

}
