package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Oficina generated by hbm2java
 */
public class Oficina implements java.io.Serializable {

	private int idOficina;
	private Territorio territorio;
	private String nombre;
	private Set hitos = new HashSet(0);

	private String nombreDetallado;
	
	public Oficina() {
	}

	public Oficina(int idOficina) {
		this.idOficina = idOficina;
	}

	public Oficina(int idOficina, Territorio territorio, String nombre,
			Set hitos) {
		this.idOficina = idOficina;
		this.territorio = territorio;
		this.nombre = nombre;
		this.hitos = hitos;
	}

	public int getIdOficina() {
		return this.idOficina;
	}

	public void setIdOficina(int idOficina) {
		this.idOficina = idOficina;
	}

	public Territorio getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

	public String getNombreDetallado() {
		return nombreDetallado;
	}

	public void setNombreDetallado(String nombreDetallado) {
		this.nombreDetallado = nombreDetallado;
	}

	

}
