package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Organo generated by hbm2java
 */
public class Organo implements java.io.Serializable {

	private int idOrgano;
	private Entidad entidad;
	private Territorio territorio;
	private String nombre;
	private Set feriados = new HashSet(0);
	private Set hitos = new HashSet(0);

	public Organo() {
	}

	public Organo(int idOrgano) {
		this.idOrgano = idOrgano;
	}

	public Organo(int idOrgano, Entidad entidad, Territorio territorio,
			String nombre, Set feriados, Set hitos) {
		this.idOrgano = idOrgano;
		this.entidad = entidad;
		this.territorio = territorio;
		this.nombre = nombre;
		this.feriados = feriados;
		this.hitos = hitos;
	}

	public int getIdOrgano() {
		return this.idOrgano;
	}

	public void setIdOrgano(int idOrgano) {
		this.idOrgano = idOrgano;
	}

	public Entidad getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}

	public Territorio getTerritorio() {
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getFeriados() {
		return this.feriados;
	}

	public void setFeriados(Set feriados) {
		this.feriados = feriados;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

}
