package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Organo generated by hbm2java
 */
public class Organo implements java.io.Serializable {

	private int idOrgano;
	private Entidad entidad;
	private Territorio territorio;
	private String nombre;
	private String codigo;
	private Set feriados = new HashSet(0);
	private Set expedientes = new HashSet(0);
	
	private String nombreDetallado;
	

	public Organo() {
	}

	public Organo(int idOrgano) {
		this.idOrgano = idOrgano;
	}

	public Organo(int idOrgano, Entidad entidad, Territorio territorio,
			String nombre, String codigo, Set feriados, Set expedientes) {
		this.idOrgano = idOrgano;
		this.entidad = entidad;
		this.territorio = territorio;
		this.nombre = nombre;
		this.codigo = codigo;
		this.feriados = feriados;
		this.expedientes = expedientes;
	}

	public int getIdOrgano() {
		return this.idOrgano;
	}

	public void setIdOrgano(int idOrgano) {
		this.idOrgano = idOrgano;
	}

	public Entidad getEntidad() {
		if(entidad ==null)
			entidad = new Entidad();
		return this.entidad;
	}

	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}

	public Territorio getTerritorio() {
		if(territorio == null)
			territorio = new Territorio();
		return this.territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getFeriados() {
		return this.feriados;
	}

	public void setFeriados(Set feriados) {
		this.feriados = feriados;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public String getNombreDetallado() {
		return nombreDetallado;
	}

	public void setNombreDetallado(String nombreDetallado) {
		this.nombreDetallado = nombreDetallado;
	}

}
