package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private BigDecimal idPersona;
	private TipoDocumento tipoDocumento;
	private Clase clase;
	private BigDecimal numeroDocumento;
	private BigDecimal codCliente;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombres;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private Serializable fechaCreacion;
	private Serializable fechaModificacion;
	private Set involucrados = new HashSet(0);
	private Set inculpados = new HashSet(0);

	public Persona() {
	}

	public Persona(BigDecimal idPersona) {
		this.idPersona = idPersona;
	}

	public Persona(BigDecimal idPersona, TipoDocumento tipoDocumento,
			Clase clase, BigDecimal numeroDocumento, BigDecimal codCliente,
			String apellidoPaterno, String apellidoMaterno, String nombres,
			String usuarioCreacion, String usuarioModificacion,
			Serializable fechaCreacion, Serializable fechaModificacion,
			Set involucrados, Set inculpados) {
		this.idPersona = idPersona;
		this.tipoDocumento = tipoDocumento;
		this.clase = clase;
		this.numeroDocumento = numeroDocumento;
		this.codCliente = codCliente;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombres = nombres;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.involucrados = involucrados;
		this.inculpados = inculpados;
	}

	public BigDecimal getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(BigDecimal idPersona) {
		this.idPersona = idPersona;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	public BigDecimal getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(BigDecimal numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public BigDecimal getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(BigDecimal codCliente) {
		this.codCliente = codCliente;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Serializable getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Serializable fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Serializable getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Serializable fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Set getInvolucrados() {
		return this.involucrados;
	}

	public void setInvolucrados(Set involucrados) {
		this.involucrados = involucrados;
	}

	public Set getInculpados() {
		return this.inculpados;
	}

	public void setInculpados(Set inculpados) {
		this.inculpados = inculpados;
	}

}
