package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private int idPersona;
	private TipoDocumento tipoDocumento;
	private Clase clase;
	private Long numeroDocumento;
	private Integer codCliente;
	private String razonSocial;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String nombreCompleto;
	private Set involucrados = new HashSet(0);
	private Set inculpados = new HashSet(0);

	private String nombreCompletoMayuscula;
	
	public Persona() {
	}

	public Persona(int idPersona) {
		this.idPersona = idPersona;
	}

	public Persona(int idPersona, TipoDocumento tipoDocumento, Clase clase,
			Long numeroDocumento, Integer codCliente, String razonSocial,
			String nombres, String apellidoPaterno, String apellidoMaterno,
			String usuarioCreacion, String usuarioModificacion,
			Date fechaCreacion, Date fechaModificacion, String nombreCompleto,
			Set involucrados, Set inculpados) {
		this.idPersona = idPersona;
		this.tipoDocumento = tipoDocumento;
		this.clase = clase;
		this.numeroDocumento = numeroDocumento;
		this.codCliente = codCliente;
		this.razonSocial = razonSocial;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.nombreCompleto = nombreCompleto;
		this.involucrados = involucrados;
		this.inculpados = inculpados;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	public Long getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(Long numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public Integer getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(Integer codCliente) {
		this.codCliente = codCliente;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public Set getInvolucrados() {
		return this.involucrados;
	}

	public void setInvolucrados(Set involucrados) {
		this.involucrados = involucrados;
	}

	public Set getInculpados() {
		return this.inculpados;
	}

	public void setInculpados(Set inculpados) {
		this.inculpados = inculpados;
	}

	public String getNombreCompletoMayuscula() {
		return nombreCompletoMayuscula;
	}

	public void setNombreCompletoMayuscula(String nombreCompletoMayuscula) {
		this.nombreCompletoMayuscula = nombreCompletoMayuscula;
	}

}
