package com.hildebrando.legal.modelo;

// Generated 30-jul-2012 11:32:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Proceso generated by hbm2java
 */
public class Proceso implements java.io.Serializable {

	private int idProceso;
	private String nombre;
	private Set hitos = new HashSet(0);
	private Set vias = new HashSet(0);

	public Proceso() {
	}

	public Proceso(int idProceso) {
		this.idProceso = idProceso;
	}

	public Proceso(int idProceso, String nombre, Set hitos, Set vias) {
		this.idProceso = idProceso;
		this.nombre = nombre;
		this.hitos = hitos;
		this.vias = vias;
	}

	public int getIdProceso() {
		return this.idProceso;
	}

	public void setIdProceso(int idProceso) {
		this.idProceso = idProceso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getHitos() {
		return this.hitos;
	}

	public void setHitos(Set hitos) {
		this.hitos = hitos;
	}

	public Set getVias() {
		return this.vias;
	}

	public void setVias(Set vias) {
		this.vias = vias;
	}

}
