package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Proceso generated by hbm2java
 */
public class Proceso implements java.io.Serializable {

	private int idProceso;
	private String nombre;
	private Set vias = new HashSet(0);
	private Set instancias = new HashSet(0);

	public Proceso() {
	}

	public Proceso(int idProceso) {
		this.idProceso = idProceso;
	}

	public Proceso(int idProceso, String nombre, Set vias, Set instancias) {
		this.idProceso = idProceso;
		this.nombre = nombre;
		this.vias = vias;
		this.instancias = instancias;
	}

	public int getIdProceso() {
		return this.idProceso;
	}

	public void setIdProceso(int idProceso) {
		this.idProceso = idProceso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getVias() {
		return this.vias;
	}

	public void setVias(Set vias) {
		this.vias = vias;
	}

	public Set getInstancias() {
		return this.instancias;
	}

	public void setInstancias(Set instancias) {
		this.instancias = instancias;
	}

}
