package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RolInvolucrado generated by hbm2java
 */
public class RolInvolucrado implements java.io.Serializable {

	private BigDecimal idRolInvolucrado;
	private String nombre;
	private Set involucrados = new HashSet(0);

	public RolInvolucrado() {
	}

	public RolInvolucrado(BigDecimal idRolInvolucrado) {
		this.idRolInvolucrado = idRolInvolucrado;
	}

	public RolInvolucrado(BigDecimal idRolInvolucrado, String nombre,
			Set involucrados) {
		this.idRolInvolucrado = idRolInvolucrado;
		this.nombre = nombre;
		this.involucrados = involucrados;
	}

	public BigDecimal getIdRolInvolucrado() {
		return this.idRolInvolucrado;
	}

	public void setIdRolInvolucrado(BigDecimal idRolInvolucrado) {
		this.idRolInvolucrado = idRolInvolucrado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getInvolucrados() {
		return this.involucrados;
	}

	public void setInvolucrados(Set involucrados) {
		this.involucrados = involucrados;
	}

}
