package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SituacionCuota generated by hbm2java
 */
public class SituacionCuota implements java.io.Serializable {

	private BigDecimal idSituacionCuota;
	private String descripcion;
	private Set cuotas = new HashSet(0);

	public SituacionCuota() {
	}

	public SituacionCuota(BigDecimal idSituacionCuota) {
		this.idSituacionCuota = idSituacionCuota;
	}

	public SituacionCuota(BigDecimal idSituacionCuota, String descripcion,
			Set cuotas) {
		this.idSituacionCuota = idSituacionCuota;
		this.descripcion = descripcion;
		this.cuotas = cuotas;
	}

	public BigDecimal getIdSituacionCuota() {
		return this.idSituacionCuota;
	}

	public void setIdSituacionCuota(BigDecimal idSituacionCuota) {
		this.idSituacionCuota = idSituacionCuota;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

}
