package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SituacionActProc generated by hbm2java
 */
public class SituacionActProc implements java.io.Serializable {

	private BigDecimal idSituacionActProc;
	private String nombre;
	private Set actividadProcesals = new HashSet(0);

	public SituacionActProc() {
	}

	public SituacionActProc(BigDecimal idSituacionActProc) {
		this.idSituacionActProc = idSituacionActProc;
	}

	public SituacionActProc(BigDecimal idSituacionActProc, String nombre,
			Set actividadProcesals) {
		this.idSituacionActProc = idSituacionActProc;
		this.nombre = nombre;
		this.actividadProcesals = actividadProcesals;
	}

	public BigDecimal getIdSituacionActProc() {
		return this.idSituacionActProc;
	}

	public void setIdSituacionActProc(BigDecimal idSituacionActProc) {
		this.idSituacionActProc = idSituacionActProc;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getActividadProcesals() {
		return this.actividadProcesals;
	}

	public void setActividadProcesals(Set actividadProcesals) {
		this.actividadProcesals = actividadProcesals;
	}

}
