package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SituacionHonorario generated by hbm2java
 */
public class SituacionHonorario implements java.io.Serializable {

	private BigDecimal idSituacionHonorario;
	private String descripcion;
	private Set honorarios = new HashSet(0);

	public SituacionHonorario() {
	}

	public SituacionHonorario(BigDecimal idSituacionHonorario) {
		this.idSituacionHonorario = idSituacionHonorario;
	}

	public SituacionHonorario(BigDecimal idSituacionHonorario,
			String descripcion, Set honorarios) {
		this.idSituacionHonorario = idSituacionHonorario;
		this.descripcion = descripcion;
		this.honorarios = honorarios;
	}

	public BigDecimal getIdSituacionHonorario() {
		return this.idSituacionHonorario;
	}

	public void setIdSituacionHonorario(BigDecimal idSituacionHonorario) {
		this.idSituacionHonorario = idSituacionHonorario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getHonorarios() {
		return this.honorarios;
	}

	public void setHonorarios(Set honorarios) {
		this.honorarios = honorarios;
	}

}
