package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Territorio generated by hbm2java
 */
public class Territorio implements java.io.Serializable {

	private int idTerritorio;
	private int ubigeo;
	private String provincia;
	private String distrito;
	private String departamento;
	private Set oficinas = new HashSet(0);
	private Set organos = new HashSet(0);
	private Set grupoBancas = new HashSet(0);

	public Territorio() {
	}

	public Territorio(int idTerritorio) {
		this.idTerritorio = idTerritorio;
	}

	public Territorio(int idTerritorio, int ubigeo, String provincia,
			String distrito, String departamento, Set oficinas, Set organos,
			Set grupoBancas) {
		this.idTerritorio = idTerritorio;
		this.ubigeo = ubigeo;
		this.provincia = provincia;
		this.distrito = distrito;
		this.departamento = departamento;
		this.oficinas = oficinas;
		this.organos = organos;
		this.grupoBancas = grupoBancas;
	}

	public int getIdTerritorio() {
		return this.idTerritorio;
	}

	public void setIdTerritorio(int idTerritorio) {
		this.idTerritorio = idTerritorio;
	}

	

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public Set getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Set oficinas) {
		this.oficinas = oficinas;
	}

	public Set getOrganos() {
		return this.organos;
	}

	public void setOrganos(Set organos) {
		this.organos = organos;
	}

	public Set getGrupoBancas() {
		return this.grupoBancas;
	}

	public void setGrupoBancas(Set grupoBancas) {
		this.grupoBancas = grupoBancas;
	}

	public int getUbigeo() {
		return ubigeo;
	}

	public void setUbigeo(int ubigeo) {
		this.ubigeo = ubigeo;
	}

}
