package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoProvision generated by hbm2java
 */
public class TipoProvision implements java.io.Serializable {

	private BigDecimal idTipoProvision;
	private String descripcion;
	private Set provisions = new HashSet(0);

	public TipoProvision() {
	}

	public TipoProvision(BigDecimal idTipoProvision) {
		this.idTipoProvision = idTipoProvision;
	}

	public TipoProvision(BigDecimal idTipoProvision, String descripcion,
			Set provisions) {
		this.idTipoProvision = idTipoProvision;
		this.descripcion = descripcion;
		this.provisions = provisions;
	}

	public BigDecimal getIdTipoProvision() {
		return this.idTipoProvision;
	}

	public void setIdTipoProvision(BigDecimal idTipoProvision) {
		this.idTipoProvision = idTipoProvision;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProvisions() {
		return this.provisions;
	}

	public void setProvisions(Set provisions) {
		this.provisions = provisions;
	}

}
