package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento implements java.io.Serializable {

	private BigDecimal idTipoDocumento;
	private String descripcion;
	private Set personas = new HashSet(0);

	public TipoDocumento() {
	}

	public TipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public TipoDocumento(BigDecimal idTipoDocumento, String descripcion,
			Set personas) {
		this.idTipoDocumento = idTipoDocumento;
		this.descripcion = descripcion;
		this.personas = personas;
	}

	public BigDecimal getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set personas) {
		this.personas = personas;
	}

}
