package com.hildebrando.legal.modelo;

// Generated 01/04/2013 11:44:24 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TipoCambio generated by hbm2java
 */
public class TipoCambio implements java.io.Serializable {

	private int idTipoCambio;
	private BigDecimal valorTipoCambio;
	private Integer moneda;
	private Date fecha;

	public TipoCambio() {
	}

	public TipoCambio(int idTipoCambio) {
		this.idTipoCambio = idTipoCambio;
	}

	public TipoCambio(int idTipoCambio, BigDecimal valorTipoCambio,
			Integer moneda, Date fecha) {
		this.idTipoCambio = idTipoCambio;
		this.valorTipoCambio = valorTipoCambio;
		this.moneda = moneda;
		this.fecha = fecha;
	}

	public int getIdTipoCambio() {
		return this.idTipoCambio;
	}

	public void setIdTipoCambio(int idTipoCambio) {
		this.idTipoCambio = idTipoCambio;
	}

	public BigDecimal getValorTipoCambio() {
		return this.valorTipoCambio;
	}

	public void setValorTipoCambio(BigDecimal valorTipoCambio) {
		this.valorTipoCambio = valorTipoCambio;
	}

	public Integer getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Integer moneda) {
		this.moneda = moneda;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
