package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoCautelar generated by hbm2java
 */
public class TipoCautelar implements java.io.Serializable {

	private BigDecimal idTipoCautelar;
	private String descripcion;
	private Set expedientes = new HashSet(0);

	public TipoCautelar() {
	}

	public TipoCautelar(BigDecimal idTipoCautelar) {
		this.idTipoCautelar = idTipoCautelar;
	}

	public TipoCautelar(BigDecimal idTipoCautelar, String descripcion,
			Set expedientes) {
		this.idTipoCautelar = idTipoCautelar;
		this.descripcion = descripcion;
		this.expedientes = expedientes;
	}

	public BigDecimal getIdTipoCautelar() {
		return this.idTipoCautelar;
	}

	public void setIdTipoCautelar(BigDecimal idTipoCautelar) {
		this.idTipoCautelar = idTipoCautelar;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

}
