package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoInvolucrado generated by hbm2java
 */
public class TipoInvolucrado implements java.io.Serializable {

	private BigDecimal idTipoInvolucrado;
	private String nombre;
	private Set involucrados = new HashSet(0);

	public TipoInvolucrado() {
	}

	public TipoInvolucrado(BigDecimal idTipoInvolucrado) {
		this.idTipoInvolucrado = idTipoInvolucrado;
	}

	public TipoInvolucrado(BigDecimal idTipoInvolucrado, String nombre,
			Set involucrados) {
		this.idTipoInvolucrado = idTipoInvolucrado;
		this.nombre = nombre;
		this.involucrados = involucrados;
	}

	public BigDecimal getIdTipoInvolucrado() {
		return this.idTipoInvolucrado;
	}

	public void setIdTipoInvolucrado(BigDecimal idTipoInvolucrado) {
		this.idTipoInvolucrado = idTipoInvolucrado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getInvolucrados() {
		return this.involucrados;
	}

	public void setInvolucrados(Set involucrados) {
		this.involucrados = involucrados;
	}

}
