package com.hildebrando.legal.modelo;

// Generated 12-jul-2012 17:35:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Via generated by hbm2java
 */
public class Via implements java.io.Serializable {

	private BigDecimal idVia;
	private Proceso proceso;
	private String nombre;

	public Via() {
	}

	public Via(BigDecimal idVia) {
		this.idVia = idVia;
	}

	public Via(BigDecimal idVia, Proceso proceso, String nombre) {
		this.idVia = idVia;
		this.proceso = proceso;
		this.nombre = nombre;
	}

	public BigDecimal getIdVia() {
		return this.idVia;
	}

	public void setIdVia(BigDecimal idVia) {
		this.idVia = idVia;
	}

	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
