package com.hildebrando.legal.modelo;

// Generated 24-jul-2012 17:43:23 by Hibernate Tools 3.4.0.CR1

/**
 * Via generated by hbm2java
 */
public class Via implements java.io.Serializable {

	private int idVia;
	private Proceso proceso;
	private String nombre;

	public Via() {
	}

	public Via(int idVia) {
		this.idVia = idVia;
	}

	public Via(int idVia, Proceso proceso, String nombre) {
		this.idVia = idVia;
		this.proceso = proceso;
		this.nombre = nombre;
	}

	public int getIdVia() {
		return this.idVia;
	}

	public void setIdVia(int idVia) {
		this.idVia = idVia;
	}

	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
