package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;
import java.util.Date;

/**
 * Correo generated by hbm2java
 */
public class Correo implements java.io.Serializable {

	private int idCorreo;
	private String from;
	private String to;
	private String cc;
	private String co;
	private String asunto;
	private Clob contenido;
	private String correoCuerpo;
	private String correoCuerpo_II;
	private int idLote;
	private Date correoFecha;
	private String correoMsje;
	private String usuario;

	public Correo() {
	}

	public Correo(int idCorreo) {
		this.idCorreo = idCorreo;
	}

	public Correo(int idCorreo, String from, String to, String cc, String co,
			String asunto, Clob contenido, String correoCuerpo, String correoCuerpoII,
			int idLote,Date correoFecha,String correoMsje, String usuario) {
		this.idCorreo = idCorreo;
		this.from = from;
		this.to = to;
		this.cc = cc;
		this.co = co;
		this.asunto = asunto;
		this.contenido = contenido;
		this.correoCuerpo=correoCuerpo;
		this.correoCuerpo_II=correoCuerpoII;
		this.idLote=idLote;
		this.correoFecha=correoFecha;
		this.correoMsje=correoMsje;
		this.usuario=usuario;
	}

	public int getIdCorreo() {
		return this.idCorreo;
	}

	public void setIdCorreo(int idCorreo) {
		this.idCorreo = idCorreo;
	}

	public String getFrom() {
		return this.from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getTo() {
		return this.to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

	public String getCo() {
		return this.co;
	}

	public void setCo(String co) {
		this.co = co;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public Clob getContenido() {
		return this.contenido;
	}

	public void setContenido(Clob contenido) {
		this.contenido = contenido;
	}

	public String getCorreoCuerpo() {
		return correoCuerpo;
	}

	public void setCorreoCuerpo(String correoCuerpo) {
		this.correoCuerpo = correoCuerpo;
	}

	public String getCorreoCuerpo_II() {
		return correoCuerpo_II;
	}

	public void setCorreoCuerpo_II(String correoCuerpo_II) {
		this.correoCuerpo_II = correoCuerpo_II;
	}

	public int getIdLote() {
		return idLote;
	}

	public void setIdLote(int idLote) {
		this.idLote = idLote;
	}

	public Date getCorreoFecha() {
		return correoFecha;
	}

	public void setCorreoFecha(Date correoFecha) {
		this.correoFecha = correoFecha;
	}

	public String getCorreoMsje() {
		return correoMsje;
	}

	public void setCorreoMsje(String correoMsje) {
		this.correoMsje = correoMsje;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
}
