package com.hildebrando.legal.modelo;

// Generated 22-oct-2012 13:27:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Entidad generated by hbm2java
 */
public class Entidad implements java.io.Serializable {

	private int idEntidad;
	private String nombre;
	private String codigo;
	private Character estado;
	private Set organos = new HashSet(0);

	public Entidad() {
	}

	public Entidad(int idEntidad) {
		this.idEntidad = idEntidad;
	}

	public Entidad(int idEntidad, String nombre, String codigo, Set organos) {
		this.idEntidad = idEntidad;
		this.nombre = nombre;
		this.codigo = codigo;
		this.organos = organos;
	}

	public int getIdEntidad() {
		return this.idEntidad;
	}

	public void setIdEntidad(int idEntidad) {
		this.idEntidad = idEntidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getOrganos() {
		return this.organos;
	}

	public void setOrganos(Set organos) {
		this.organos = organos;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
