package com.hildebrando.legal.modelo;

// Generated 23-ago-2012 20:40:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FormaConclusion generated by hbm2java
 */
public class FormaConclusion implements java.io.Serializable {

	private int idFormaConclusion;
	private String descripcion;
	private Character estado;
	private Set expedientes = new HashSet(0);

	public FormaConclusion() {
	}

	public FormaConclusion(int idFormaConclusion) {
		this.idFormaConclusion = idFormaConclusion;
	}

	public FormaConclusion(int idFormaConclusion, String descripcion,
			Set expedientes) {
		this.idFormaConclusion = idFormaConclusion;
		this.descripcion = descripcion;
		this.expedientes = expedientes;
	}

	public int getIdFormaConclusion() {
		return this.idFormaConclusion;
	}

	public void setIdFormaConclusion(int idFormaConclusion) {
		this.idFormaConclusion = idFormaConclusion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
