package com.hildebrando.legal.modelo;
// Generated 25-jun-2012 10:32:06 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * QrtzHistorial generated by hbm2java
 */
public class QrtzHistorial  implements java.io.Serializable {


     private int idhistorial;
     private String idtriggername;
     private String idtriggergroup;
     private String idjobname;
     private String idjobgroup;
     private Date fechainicio;
     private Date fechafin;
     private String estado;

    public QrtzHistorial() {
    }

	
    public QrtzHistorial(int idhistorial) {
        this.idhistorial = idhistorial;
    }
    public QrtzHistorial(int idhistorial, String idtriggername, String idtriggergroup, String idjobname, String idjobgroup, Date fechainicio, Date fechafin, String estado) {
       this.idhistorial = idhistorial;
       this.idtriggername = idtriggername;
       this.idtriggergroup = idtriggergroup;
       this.idjobname = idjobname;
       this.idjobgroup = idjobgroup;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.estado = estado;
    }
   
    public int getIdhistorial() {
        return this.idhistorial;
    }
    
    public void setIdhistorial(int idhistorial) {
        this.idhistorial = idhistorial;
    }
    public String getIdtriggername() {
        return this.idtriggername;
    }
    
    public void setIdtriggername(String idtriggername) {
        this.idtriggername = idtriggername;
    }
    public String getIdtriggergroup() {
        return this.idtriggergroup;
    }
    
    public void setIdtriggergroup(String idtriggergroup) {
        this.idtriggergroup = idtriggergroup;
    }
    public String getIdjobname() {
        return this.idjobname;
    }
    
    public void setIdjobname(String idjobname) {
        this.idjobname = idjobname;
    }
    public String getIdjobgroup() {
        return this.idjobgroup;
    }
    
    public void setIdjobgroup(String idjobgroup) {
        this.idjobgroup = idjobgroup;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


