package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RolInvolucrado generated by hbm2java
 */
public class RolInvolucrado implements java.io.Serializable {

	private int idRolInvolucrado;
	private String nombre;
	private Character estado;
	private Set involucrados = new HashSet(0);

	public RolInvolucrado() {
	}

	public RolInvolucrado(int idRolInvolucrado) {
		this.idRolInvolucrado = idRolInvolucrado;
	}

	public RolInvolucrado(int idRolInvolucrado, String nombre, Set involucrados) {
		this.idRolInvolucrado = idRolInvolucrado;
		this.nombre = nombre;
		this.involucrados = involucrados;
	}

	public int getIdRolInvolucrado() {
		return this.idRolInvolucrado;
	}

	public void setIdRolInvolucrado(int idRolInvolucrado) {
		this.idRolInvolucrado = idRolInvolucrado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getInvolucrados() {
		return this.involucrados;
	}

	public void setInvolucrados(Set involucrados) {
		this.involucrados = involucrados;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
