package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SituacionActProc generated by hbm2java
 */
public class SituacionActProc implements java.io.Serializable {

	private int idSituacionActProc;
	private String nombre;
	private Character estado;
	private Set actividadProcesals = new HashSet(0);

	public SituacionActProc() {
	}

	public SituacionActProc(int idSituacionActProc) {
		this.idSituacionActProc = idSituacionActProc;
	}

	public SituacionActProc(int idSituacionActProc, String nombre,
			Set actividadProcesals) {
		this.idSituacionActProc = idSituacionActProc;
		this.nombre = nombre;
		this.actividadProcesals = actividadProcesals;
	}

	public int getIdSituacionActProc() {
		return this.idSituacionActProc;
	}

	public void setIdSituacionActProc(int idSituacionActProc) {
		this.idSituacionActProc = idSituacionActProc;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getActividadProcesals() {
		return this.actividadProcesals;
	}

	public void setActividadProcesals(Set actividadProcesals) {
		this.actividadProcesals = actividadProcesals;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
