package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoExpediente generated by hbm2java
 */
public class TipoExpediente implements java.io.Serializable {

	private int idTipoExpediente;
	private String nombre;
	private Character estado;
	private Set expedientes = new HashSet(0);

	public TipoExpediente() {
	}

	public TipoExpediente(int idTipoExpediente) {
		this.idTipoExpediente = idTipoExpediente;
	}

	public TipoExpediente(int idTipoExpediente, String nombre, Set expedientes) {
		this.idTipoExpediente = idTipoExpediente;
		this.nombre = nombre;
		this.expedientes = expedientes;
	}

	public int getIdTipoExpediente() {
		return this.idTipoExpediente;
	}

	public void setIdTipoExpediente(int idTipoExpediente) {
		this.idTipoExpediente = idTipoExpediente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
