package com.hildebrando.legal.modelo;

// Generated 22-oct-2012 13:27:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ubigeo generated by hbm2java
 */
public class Ubigeo implements java.io.Serializable {

	private String codDist;
	private String distrito;
	private String codProv;
	private String provincia;
	private String codDep;
	private String departamento;
	private Character estado;
	private Set organos = new HashSet(0);
	private Set feriados = new HashSet(0);
	private Set oficinas = new HashSet(0);
	
	private String descripcionDistrito;

	public Ubigeo() {
	}

	public Ubigeo(String codDist, String codProv, String codDep) {
		this.codDist = codDist;
		this.codProv = codProv;
		this.codDep = codDep;
	}

	public Ubigeo(String codDist, String distrito, String codProv,
			String provincia, String codDep, String departamento, Set organos,
			Set feriados, Set oficinas) {
		this.codDist = codDist;
		this.distrito = distrito;
		this.codProv = codProv;
		this.provincia = provincia;
		this.codDep = codDep;
		this.departamento = departamento;
		this.organos = organos;
		this.feriados = feriados;
		this.oficinas = oficinas;
	}

	public String getCodDist() {
		return this.codDist;
	}

	public void setCodDist(String codDist) {
		this.codDist = codDist;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getCodProv() {
		return this.codProv;
	}

	public void setCodProv(String codProv) {
		this.codProv = codProv;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getCodDep() {
		return this.codDep;
	}

	public void setCodDep(String codDep) {
		this.codDep = codDep;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public Set getOrganos() {
		return this.organos;
	}

	public void setOrganos(Set organos) {
		this.organos = organos;
	}

	public Set getFeriados() {
		return this.feriados;
	}

	public void setFeriados(Set feriados) {
		this.feriados = feriados;
	}

	public Set getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Set oficinas) {
		this.oficinas = oficinas;
	}

	public String getDescripcionDistrito() {
		return descripcionDistrito;
	}

	public void setDescripcionDistrito(String descripcionDistrito) {
		this.descripcionDistrito = descripcionDistrito;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}
	
}
