
--Mejoras SGL [10-2013]

--Se agregan las columnas 'Estado' a las siguientes tablas
ALTER TABLE GESLEG.PERSONA DROP COLUMN ESTADO;
ALTER TABLE GESLEG.ORGANO DROP COLUMN ESTADO;
ALTER TABLE GESLEG.ABOGADO DROP COLUMN ESTADO;
COMMIT;
ALTER TABLE GESLEG.PERSONA ADD ESTADO CHAR(1) DEFAULT 'A' NOT NULL;
ALTER TABLE GESLEG.ORGANO ADD ESTADO CHAR(1) DEFAULT 'A' NOT NULL;
ALTER TABLE GESLEG.ABOGADO ADD ESTADO CHAR(1) DEFAULT 'A' NOT NULL;

--