package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Estudio generated by hbm2java
 */
public class Estudio implements java.io.Serializable {

	private int idEstudio;
	private Long ruc;
	private String direccion;
	private String telefono;
	private String correo;
	private String nombre;
	private String fax;
	private String codigo;
	private Character estado;
	private Set abogadoEstudios = new HashSet(0);

	public Estudio() {
	}

	public Estudio(int idEstudio) {
		this.idEstudio = idEstudio;
	}

	public Estudio(int idEstudio, Long ruc, String direccion, String telefono,
			String correo, String nombre, String fax, String codigo,
			Set abogadoEstudios) {
		this.idEstudio = idEstudio;
		this.ruc = ruc;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.nombre = nombre;
		this.fax = fax;
		this.codigo = codigo;
		this.abogadoEstudios = abogadoEstudios;
	}

	public int getIdEstudio() {
		return this.idEstudio;
	}

	public void setIdEstudio(int idEstudio) {
		this.idEstudio = idEstudio;
	}

	public Long getRuc() {
		return this.ruc;
	}

	public void setRuc(Long ruc) {
		this.ruc = ruc;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getAbogadoEstudios() {
		return this.abogadoEstudios;
	}

	public void setAbogadoEstudios(Set abogadoEstudios) {
		this.abogadoEstudios = abogadoEstudios;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
