package com.hildebrando.legal.modelo;

// Generated 22-oct-2012 12:21:21 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * GrupoBanca generated by hbm2java
 */
public class GrupoBanca implements java.io.Serializable {

	private int idGrupoBanca;
	private String descripcion;
	private Character estado;
	private Set territorios = new HashSet(0);

	public GrupoBanca() {
	}

	public GrupoBanca(int idGrupoBanca) {
		this.idGrupoBanca = idGrupoBanca;
	}

	public GrupoBanca(int idGrupoBanca, Set territorios) {
		this.idGrupoBanca = idGrupoBanca;
		this.territorios = territorios;
	}

	public int getIdGrupoBanca() {
		return this.idGrupoBanca;
	}

	public void setIdGrupoBanca(int idGrupoBanca) {
		this.idGrupoBanca = idGrupoBanca;
	}

	public Set getTerritorios() {
		return this.territorios;
	}

	public void setTerritorios(Set territorios) {
		this.territorios = territorios;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}
}
