package com.hildebrando.legal.modelo;

// Generated 10-ago-2012 17:25:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Instancia generated by hbm2java
 */
public class Instancia implements java.io.Serializable {

	private int idInstancia;
	private Via via;
	private String nombre;
	private Integer prioridad;
	private Character estado;
	private Set expedientes = new HashSet(0);

	public Instancia() {
	}

	public Instancia(int idInstancia) {
		this.idInstancia = idInstancia;
	}

	public Instancia(int idInstancia, Via via, Character estado, String nombre,
			Integer prioridad, Set expedientes) {
		this.idInstancia = idInstancia;
		this.via = via;
		this.nombre = nombre;
		this.estado= estado;
		this.prioridad = prioridad;
		this.expedientes = expedientes;
	}

	public int getIdInstancia() {
		return this.idInstancia;
	}

	public void setIdInstancia(int idInstancia) {
		this.idInstancia = idInstancia;
	}

	public Via getVia() {
		return this.via;
	}

	public void setVia(Via via) {
		this.via = via;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public Integer getPrioridad() {
		return prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
