package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Recurrencia generated by hbm2java
 */
public class Recurrencia implements java.io.Serializable {

	private int idRecurrencia;
	private String nombre;
	private Character estado;
	private Set expedientes = new HashSet(0);

	public Recurrencia() {
	}

	public Recurrencia(int idRecurrencia) {
		this.idRecurrencia = idRecurrencia;
	}

	public Recurrencia(int idRecurrencia, String nombre, Set expedientes) {
		this.idRecurrencia = idRecurrencia;
		this.nombre = nombre;
		this.expedientes = expedientes;
	}

	public int getIdRecurrencia() {
		return this.idRecurrencia;
	}

	public void setIdRecurrencia(int idRecurrencia) {
		this.idRecurrencia = idRecurrencia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
