package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Riesgo generated by hbm2java
 */
public class Riesgo implements java.io.Serializable {

	private int idRiesgo;
	private String descripcion;
	private Character estado;
	private Set expedientes = new HashSet(0);

	public Riesgo() {
	}

	public Riesgo(int idRiesgo) {
		this.idRiesgo = idRiesgo;
	}

	public Riesgo(int idRiesgo, String descripcion, Set expedientes) {
		this.idRiesgo = idRiesgo;
		this.descripcion = descripcion;
		this.expedientes = expedientes;
	}

	public int getIdRiesgo() {
		return this.idRiesgo;
	}

	public void setIdRiesgo(int idRiesgo) {
		this.idRiesgo = idRiesgo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(Set expedientes) {
		this.expedientes = expedientes;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}
}
