package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private int idRol;
	private String descripcion;
	private Character estado;
	private Proceso proceso;
	private Set usuarios = new HashSet(0);

	public Rol() {
	}

	public Rol(int idRol) {
		this.idRol = idRol;
	}

	public Rol(int idRol, String descripcion, Character estado,Proceso proceso,
			Set usuarios) {
		this.idRol = idRol;
		this.descripcion = descripcion;
		this.estado = estado;
		this.proceso = proceso;
		this.usuarios = usuarios;
	}

	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Proceso getProceso() {
		return proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}


}
