package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SituacionInculpado generated by hbm2java
 */
public class SituacionInculpado implements java.io.Serializable {

	private int idSituacionInculpado;
	private String nombre;
	private Character estado;
	private Set inculpados = new HashSet(0);

	public SituacionInculpado() {
	}

	public SituacionInculpado(int idSituacionInculpado) {
		this.idSituacionInculpado = idSituacionInculpado;
	}

	public SituacionInculpado(int idSituacionInculpado, String nombre,
			Set inculpados) {
		this.idSituacionInculpado = idSituacionInculpado;
		this.nombre = nombre;
		this.inculpados = inculpados;
	}

	public int getIdSituacionInculpado() {
		return this.idSituacionInculpado;
	}

	public void setIdSituacionInculpado(int idSituacionInculpado) {
		this.idSituacionInculpado = idSituacionInculpado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getInculpados() {
		return this.inculpados;
	}

	public void setInculpados(Set inculpados) {
		this.inculpados = inculpados;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
