package com.hildebrando.legal.modelo;

// Generated 01-ago-2012 12:12:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoHonorario generated by hbm2java
 */
public class TipoHonorario implements java.io.Serializable {

	private int idTipoHonorario;
	private String descripcion;
	private Character estado;
	private Set honorarios = new HashSet(0);

	public TipoHonorario() {
	}

	public TipoHonorario(int idTipoHonorario) {
		this.idTipoHonorario = idTipoHonorario;
	}

	public TipoHonorario(int idTipoHonorario, String descripcion, Set honorarios) {
		this.idTipoHonorario = idTipoHonorario;
		this.descripcion = descripcion;
		this.honorarios = honorarios;
	}

	public int getIdTipoHonorario() {
		return this.idTipoHonorario;
	}

	public void setIdTipoHonorario(int idTipoHonorario) {
		this.idTipoHonorario = idTipoHonorario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getHonorarios() {
		return this.honorarios;
	}

	public void setHonorarios(Set honorarios) {
		this.honorarios = honorarios;
	}

	public Character getEstado() {
		return estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
